const COUNTRIES = [
  { CountryID: 1, Name: 'DE' },
  { CountryID: 2, Name: 'AF' },
  { CountryID: 3, Name: 'AL' },
  { CountryID: 4, Name: 'DZ' },
  { CountryID: 5, Name: 'AS' },
  { CountryID: 6, Name: 'AD' },
  { CountryID: 7, Name: 'AO' },
  { CountryID: 8, Name: 'AI' },
  { CountryID: 9, Name: 'AQ' },
  { CountryID: 10, Name: 'AG' },
  { CountryID: 11, Name: 'AR' },
  { CountryID: 12, Name: 'AM' },
  { CountryID: 13, Name: 'AW' },
  { CountryID: 14, Name: 'AU' },
  { CountryID: 15, Name: 'AT' },
  { CountryID: 16, Name: 'AZ' },
  { CountryID: 17, Name: 'BS' },
  { CountryID: 18, Name: 'BH' },
  { CountryID: 19, Name: 'BD' },
  { CountryID: 20, Name: 'BB' },
  { CountryID: 21, Name: 'BY' },
  { CountryID: 22, Name: 'BE' },
  { CountryID: 23, Name: 'BZ' },
  { CountryID: 24, Name: 'BJ' },
  { CountryID: 25, Name: 'BM' },
  { CountryID: 26, Name: 'BT' },
  { CountryID: 27, Name: 'BO' },
  { CountryID: 28, Name: 'BA' },
  { CountryID: 29, Name: 'BW' },
  { CountryID: 30, Name: 'BR' },
  { CountryID: 31, Name: 'IO' },
  { CountryID: 32, Name: 'VG' },
  { CountryID: 33, Name: 'BN' },
  { CountryID: 34, Name: 'BG' },
  { CountryID: 35, Name: 'BF' },
  { CountryID: 36, Name: 'MM' },
  { CountryID: 37, Name: 'BI' },
  { CountryID: 38, Name: 'KH' },
  { CountryID: 39, Name: 'CM' },
  { CountryID: 40, Name: 'CA' },
  { CountryID: 41, Name: 'CV' },
  { CountryID: 42, Name: 'KY' },
  { CountryID: 43, Name: 'CF' },
  { CountryID: 44, Name: 'TD' },
  { CountryID: 45, Name: 'CL' },
  { CountryID: 46, Name: 'CN' },
  { CountryID: 47, Name: 'CX' },
  { CountryID: 48, Name: 'CC' },
  { CountryID: 49, Name: 'CO' },
  { CountryID: 50, Name: 'KM' },
  { CountryID: 51, Name: 'CG' },
  { CountryID: 52, Name: 'CD' },
  { CountryID: 53, Name: 'CK' },
  { CountryID: 54, Name: 'CR' },
  { CountryID: 55, Name: 'HR' },
  { CountryID: 56, Name: 'CU' },
  { CountryID: 57, Name: 'CY' },
  { CountryID: 58, Name: 'CZ' },
  { CountryID: 59, Name: 'DK' },
  { CountryID: 60, Name: 'DJ' },
  { CountryID: 61, Name: 'DM' },
  { CountryID: 62, Name: 'DO' },
  { CountryID: 63, Name: 'TL' },
  { CountryID: 64, Name: 'EC' },
  { CountryID: 65, Name: 'EG' },
  { CountryID: 66, Name: 'SV' },
  { CountryID: 67, Name: 'GQ' },
  { CountryID: 68, Name: 'ER' },
  { CountryID: 69, Name: 'EE' },
  { CountryID: 70, Name: 'ET' },
  { CountryID: 71, Name: 'FK' },
  { CountryID: 72, Name: 'FO' },
  { CountryID: 73, Name: 'FJ' },
  { CountryID: 74, Name: 'FI' },
  { CountryID: 75, Name: 'FR' },
  { CountryID: 76, Name: 'PF' },
  { CountryID: 77, Name: 'GA' },
  { CountryID: 78, Name: 'GM' },
  { CountryID: 79, Name: 'GE' },
  { CountryID: 80, Name: 'GH' },
  { CountryID: 81, Name: 'GI' },
  { CountryID: 82, Name: 'GR' },
  { CountryID: 83, Name: 'GL' },
  { CountryID: 84, Name: 'GD' },
  { CountryID: 85, Name: 'GU' },
  { CountryID: 86, Name: 'GT' },
  { CountryID: 87, Name: 'GN' },
  { CountryID: 88, Name: 'GW' },
  { CountryID: 89, Name: 'GY' },
  { CountryID: 90, Name: 'HT' },
  { CountryID: 91, Name: 'HN' },
  { CountryID: 92, Name: 'HK' },
  { CountryID: 93, Name: 'HU' },
  { CountryID: 94, Name: 'IS' },
  { CountryID: 95, Name: 'IN' },
  { CountryID: 96, Name: 'ID' },
  { CountryID: 97, Name: 'IR' },
  { CountryID: 98, Name: 'IQ' },
  { CountryID: 99, Name: 'IE' },
  { CountryID: 100, Name: 'IM' },
  { CountryID: 101, Name: 'IL' },
  { CountryID: 102, Name: 'IT' },
  { CountryID: 103, Name: 'CI' },
  { CountryID: 104, Name: 'JM' },
  { CountryID: 105, Name: 'JP' },
  { CountryID: 106, Name: 'JE' },
  { CountryID: 107, Name: 'JO' },
  { CountryID: 108, Name: 'KZ' },
  { CountryID: 109, Name: 'KE' },
  { CountryID: 110, Name: 'KI' },
  { CountryID: 111, Name: 'KW' },
  { CountryID: 112, Name: 'KG' },
  { CountryID: 113, Name: 'LA' },
  { CountryID: 114, Name: 'LV' },
  { CountryID: 115, Name: 'LB' },
  { CountryID: 116, Name: 'LS' },
  { CountryID: 117, Name: 'LR' },
  { CountryID: 118, Name: 'LY' },
  { CountryID: 119, Name: 'LI' },
  { CountryID: 120, Name: 'LT' },
  { CountryID: 121, Name: 'LU' },
  { CountryID: 122, Name: 'MO' },
  { CountryID: 123, Name: 'MK' },
  { CountryID: 124, Name: 'MG' },
  { CountryID: 125, Name: 'MW' },
  { CountryID: 126, Name: 'MY' },
  { CountryID: 127, Name: 'MV' },
  { CountryID: 128, Name: 'ML' },
  { CountryID: 129, Name: 'MT' },
  { CountryID: 130, Name: 'MH' },
  { CountryID: 131, Name: 'MR' },
  { CountryID: 132, Name: 'MU' },
  { CountryID: 133, Name: 'YT' },
  { CountryID: 134, Name: 'MX' },
  { CountryID: 135, Name: 'FM' },
  { CountryID: 136, Name: 'MD' },
  { CountryID: 137, Name: 'MC' },
  { CountryID: 138, Name: 'MN' },
  { CountryID: 139, Name: 'ME' },
  { CountryID: 140, Name: 'MS' },
  { CountryID: 141, Name: 'MA' },
  { CountryID: 142, Name: 'MZ' },
  { CountryID: 143, Name: 'NA' },
  { CountryID: 144, Name: 'NR' },
  { CountryID: 145, Name: 'NP' },
  { CountryID: 146, Name: 'NL' },
  { CountryID: 147, Name: 'NC' },
  { CountryID: 148, Name: 'NZ' },
  { CountryID: 149, Name: 'NI' },
  { CountryID: 150, Name: 'NE' },
  { CountryID: 151, Name: 'NG' },
  { CountryID: 152, Name: 'NU' },
  { CountryID: 153, Name: 'NF' },
  { CountryID: 154, Name: 'MP' },
  { CountryID: 155, Name: 'KP' },
  { CountryID: 156, Name: 'NO' },
  { CountryID: 157, Name: 'OM' },
  { CountryID: 158, Name: 'PK' },
  { CountryID: 159, Name: 'PW' },
  { CountryID: 160, Name: 'PA' },
  { CountryID: 161, Name: 'PG' },
  { CountryID: 162, Name: 'PY' },
  { CountryID: 163, Name: 'PE' },
  { CountryID: 164, Name: 'PH' },
  { CountryID: 165, Name: 'PN' },
  { CountryID: 166, Name: 'PL' },
  { CountryID: 167, Name: 'PT' },
  { CountryID: 168, Name: 'PR' },
  { CountryID: 169, Name: 'QA' },
  { CountryID: 170, Name: 'RO' },
  { CountryID: 171, Name: 'RU' },
  { CountryID: 172, Name: 'RW' },
  { CountryID: 173, Name: 'BL' },
  { CountryID: 174, Name: 'WS' },
  { CountryID: 175, Name: 'SM' },
  { CountryID: 176, Name: 'ST' },
  { CountryID: 177, Name: 'SA' },
  { CountryID: 178, Name: 'SN' },
  { CountryID: 179, Name: 'RS' },
  { CountryID: 180, Name: 'SC' },
  { CountryID: 181, Name: 'SL' },
  { CountryID: 182, Name: 'SG' },
  { CountryID: 183, Name: 'SK' },
  { CountryID: 184, Name: 'SI' },
  { CountryID: 185, Name: 'SB' },
  { CountryID: 186, Name: 'SO' },
  { CountryID: 187, Name: 'ZA' },
  { CountryID: 188, Name: 'KR' },
  { CountryID: 189, Name: 'SS' },
  { CountryID: 190, Name: 'ES' },
  { CountryID: 191, Name: 'LK' },
  { CountryID: 192, Name: 'SH' },
  { CountryID: 193, Name: 'KN' },
  { CountryID: 194, Name: 'LC' },
  { CountryID: 195, Name: 'MF' },
  { CountryID: 196, Name: 'PM' },
  { CountryID: 197, Name: 'VC' },
  { CountryID: 198, Name: 'SD' },
  { CountryID: 199, Name: 'SR' },
  { CountryID: 200, Name: 'SJ' },
  { CountryID: 201, Name: 'SZ' },
  { CountryID: 202, Name: 'SE' },
  { CountryID: 203, Name: 'CH' },
  { CountryID: 204, Name: 'SY' },
  { CountryID: 205, Name: 'TW' },
  { CountryID: 206, Name: 'TJ' },
  { CountryID: 207, Name: 'TZ' },
  { CountryID: 208, Name: 'TH' },
  { CountryID: 209, Name: 'TG' },
  { CountryID: 210, Name: 'TK' },
  { CountryID: 211, Name: 'TO' },
  { CountryID: 212, Name: 'TT' },
  { CountryID: 213, Name: 'TN' },
  { CountryID: 214, Name: 'TR' },
  { CountryID: 215, Name: 'TM' },
  { CountryID: 216, Name: 'TC' },
  { CountryID: 217, Name: 'TV' },
  { CountryID: 218, Name: 'AE' },
  { CountryID: 219, Name: 'UG' },
  { CountryID: 220, Name: 'GB' },
  { CountryID: 221, Name: 'UA' },
  { CountryID: 222, Name: 'UY' },
  { CountryID: 223, Name: 'US' },
  { CountryID: 224, Name: 'UZ' },
  { CountryID: 225, Name: 'VU' },
  { CountryID: 226, Name: 'VA' },
  { CountryID: 227, Name: 'VE' },
  { CountryID: 228, Name: 'VN' },
  { CountryID: 229, Name: 'VI' },
  { CountryID: 230, Name: 'WF' },
  { CountryID: 231, Name: 'YE' },
  { CountryID: 232, Name: 'ZM' },
  { CountryID: 233, Name: 'ZW' },
  { CountryID: 234, Name: 'PS' },
  { CountryID: 235, Name: 'RE' }
];

const MOBILE_OPERATORS = [
  { MobileOperatorID: 1, CountryID: 1, CountyName: 'DE', Name: 'AIRDATA' },
  { MobileOperatorID: 2, CountryID: 1, CountyName: 'DE', Name: 'DEBITEL' },
  { MobileOperatorID: 3, CountryID: 1, CountyName: 'DE', Name: 'O2' },
  { MobileOperatorID: 4, CountryID: 1, CountyName: 'DE', Name: 'TELEKOM' },
  { MobileOperatorID: 5, CountryID: 1, CountyName: 'DE', Name: 'VODAFONE' },
  { MobileOperatorID: 6, CountryID: 1, CountyName: 'DE', Name: 'WiFi' },
  { MobileOperatorID: 7, CountryID: 2, CountyName: 'AF', Name: 'AWCC' },
  { MobileOperatorID: 8, CountryID: 2, CountyName: 'AF', Name: 'ETISALAT' },
  { MobileOperatorID: 9, CountryID: 2, CountyName: 'AF', Name: 'MTN' },
  { MobileOperatorID: 10, CountryID: 2, CountyName: 'AF', Name: 'ROSHAN' },
  { MobileOperatorID: 11, CountryID: 2, CountyName: 'AF', Name: 'WASEL' },
  { MobileOperatorID: 12, CountryID: 2, CountyName: 'AF', Name: 'WiFi' },
  { MobileOperatorID: 13, CountryID: 3, CountyName: 'AL', Name: 'EAGLE MOBILE' },
  { MobileOperatorID: 14, CountryID: 3, CountyName: 'AL', Name: 'PLUS COMMUNICATION' },
  { MobileOperatorID: 15, CountryID: 3, CountyName: 'AL', Name: 'TELEKOM.AL' },
  { MobileOperatorID: 16, CountryID: 3, CountyName: 'AL', Name: 'VODAFONE' },
  { MobileOperatorID: 17, CountryID: 3, CountyName: 'AL', Name: 'WiFi' },
  { MobileOperatorID: 18, CountryID: 4, CountyName: 'DZ', Name: 'DJEZZY' },
  { MobileOperatorID: 19, CountryID: 4, CountyName: 'DZ', Name: 'MOBILIS' },
  { MobileOperatorID: 20, CountryID: 4, CountyName: 'DZ', Name: 'OOREDOO' },
  { MobileOperatorID: 21, CountryID: 4, CountyName: 'DZ', Name: 'WiFi' },
  { MobileOperatorID: 22, CountryID: 5, CountyName: 'AS', Name: 'WiFi' },
  { MobileOperatorID: 23, CountryID: 6, CountyName: 'AD', Name: 'WiFi' },
  { MobileOperatorID: 24, CountryID: 7, CountyName: 'AO', Name: 'MOVICEL' },
  { MobileOperatorID: 25, CountryID: 7, CountyName: 'AO', Name: 'UNITEL' },
  { MobileOperatorID: 26, CountryID: 7, CountyName: 'AO', Name: 'WiFi' },
  { MobileOperatorID: 27, CountryID: 8, CountyName: 'AI', Name: 'WiFi' },
  { MobileOperatorID: 28, CountryID: 9, CountyName: 'AQ', Name: 'WiFi' },
  { MobileOperatorID: 29, CountryID: 10, CountyName: 'AG', Name: 'DIGICEL' },
  { MobileOperatorID: 30, CountryID: 10, CountyName: 'AG', Name: 'FLOW' },
  { MobileOperatorID: 31, CountryID: 10, CountyName: 'AG', Name: 'WiFi' },
  { MobileOperatorID: 32, CountryID: 11, CountyName: 'AR', Name: 'CLARO' },
  { MobileOperatorID: 33, CountryID: 11, CountyName: 'AR', Name: 'MOVISTAR' },
  { MobileOperatorID: 34, CountryID: 11, CountyName: 'AR', Name: 'NEXTEL' },
  { MobileOperatorID: 35, CountryID: 11, CountyName: 'AR', Name: 'PERSONAL' },
  { MobileOperatorID: 36, CountryID: 11, CountyName: 'AR', Name: 'WiFi' },
  { MobileOperatorID: 37, CountryID: 12, CountyName: 'AM', Name: 'BEELINE' },
  { MobileOperatorID: 38, CountryID: 12, CountyName: 'AM', Name: 'UCOM' },
  { MobileOperatorID: 39, CountryID: 12, CountyName: 'AM', Name: 'VIVACELL-MTS' },
  { MobileOperatorID: 40, CountryID: 12, CountyName: 'AM', Name: 'WiFi' },
  { MobileOperatorID: 41, CountryID: 13, CountyName: 'AW', Name: 'DIGICEL' },
  { MobileOperatorID: 42, CountryID: 13, CountyName: 'AW', Name: 'SETAR' },
  { MobileOperatorID: 43, CountryID: 13, CountyName: 'AW', Name: 'WiFi' },
  { MobileOperatorID: 44, CountryID: 14, CountyName: 'AU', Name: 'AAPT' },
  { MobileOperatorID: 45, CountryID: 14, CountyName: 'AU', Name: 'IINET LTD' },
  { MobileOperatorID: 46, CountryID: 14, CountyName: 'AU', Name: 'LYCAMOBILE' },
  { MobileOperatorID: 47, CountryID: 14, CountyName: 'AU', Name: 'OPTUS' },
  { MobileOperatorID: 48, CountryID: 14, CountyName: 'AU', Name: 'QUEENSLAND RAIL LIMITED' },
  { MobileOperatorID: 49, CountryID: 14, CountyName: 'AU', Name: 'TELSTRA' },
  { MobileOperatorID: 50, CountryID: 14, CountyName: 'AU', Name: 'VODAFONE' },
  { MobileOperatorID: 51, CountryID: 14, CountyName: 'AU', Name: 'WiFi' },
  { MobileOperatorID: 52, CountryID: 15, CountyName: 'AT', Name: '3' },
  { MobileOperatorID: 53, CountryID: 15, CountyName: 'AT', Name: 'A1.NET' },
  { MobileOperatorID: 54, CountryID: 15, CountyName: 'AT', Name: 'MASS RESPONSE SERVICE GMBH' },
  { MobileOperatorID: 55, CountryID: 15, CountyName: 'AT', Name: 'T-MOBILE AT' },
  { MobileOperatorID: 56, CountryID: 15, CountyName: 'AT', Name: 'TELE2 TELECOMMUNICATION GMBH' },
  { MobileOperatorID: 57, CountryID: 15, CountyName: 'AT', Name: 'TELE2MOBIL' },
  { MobileOperatorID: 58, CountryID: 15, CountyName: 'AT', Name: 'UPC' },
  { MobileOperatorID: 59, CountryID: 15, CountyName: 'AT', Name: 'WiFi' },
  { MobileOperatorID: 60, CountryID: 16, CountyName: 'AZ', Name: 'AZERCELL' },
  { MobileOperatorID: 61, CountryID: 16, CountyName: 'AZ', Name: 'BAKCELL' },
  { MobileOperatorID: 62, CountryID: 16, CountyName: 'AZ', Name: 'NAR MOBILE' },
  { MobileOperatorID: 63, CountryID: 16, CountyName: 'AZ', Name: 'NAXTEL' },
  { MobileOperatorID: 64, CountryID: 16, CountyName: 'AZ', Name: 'WiFi' },
  { MobileOperatorID: 65, CountryID: 17, CountyName: 'BS', Name: 'BTC' },
  { MobileOperatorID: 66, CountryID: 17, CountyName: 'BS', Name: 'WiFi' },
  { MobileOperatorID: 67, CountryID: 18, CountyName: 'BH', Name: 'BATELCO' },
  { MobileOperatorID: 68, CountryID: 18, CountyName: 'BH', Name: 'VIVA BAHRAIN' },
  { MobileOperatorID: 69, CountryID: 18, CountyName: 'BH', Name: 'WiFi' },
  { MobileOperatorID: 70, CountryID: 18, CountyName: 'BH', Name: 'ZAIN BH' },
  { MobileOperatorID: 71, CountryID: 19, CountyName: 'BD', Name: 'AIRTEL' },
  { MobileOperatorID: 72, CountryID: 19, CountyName: 'BD', Name: 'BANGALINK' },
  { MobileOperatorID: 73, CountryID: 19, CountyName: 'BD', Name: 'GRAMEENPHONE' },
  { MobileOperatorID: 74, CountryID: 19, CountyName: 'BD', Name: 'ROBI' },
  { MobileOperatorID: 75, CountryID: 19, CountyName: 'BD', Name: 'TELETALK' },
  { MobileOperatorID: 76, CountryID: 19, CountyName: 'BD', Name: 'WiFi' },
  { MobileOperatorID: 77, CountryID: 20, CountyName: 'BB', Name: 'DIGICEL' },
  { MobileOperatorID: 78, CountryID: 20, CountyName: 'BB', Name: 'FLOW' },
  { MobileOperatorID: 79, CountryID: 20, CountyName: 'BB', Name: 'SUNBEACH COMMUNICATIONS' },
  { MobileOperatorID: 80, CountryID: 20, CountyName: 'BB', Name: 'WiFi' },
  { MobileOperatorID: 81, CountryID: 21, CountyName: 'BY', Name: 'LIFE' },
  { MobileOperatorID: 82, CountryID: 21, CountyName: 'BY', Name: 'MTS' },
  { MobileOperatorID: 83, CountryID: 21, CountyName: 'BY', Name: 'VELCOM' },
  { MobileOperatorID: 84, CountryID: 21, CountyName: 'BY', Name: 'WiFi' },
  { MobileOperatorID: 85, CountryID: 22, CountyName: 'BE', Name: 'BASE' },
  { MobileOperatorID: 86, CountryID: 22, CountyName: 'BE', Name: 'ORANGE' },
  { MobileOperatorID: 87, CountryID: 22, CountyName: 'BE', Name: 'PROXIMUS' },
  { MobileOperatorID: 88, CountryID: 22, CountyName: 'BE', Name: 'WiFi' },
  { MobileOperatorID: 89, CountryID: 23, CountyName: 'BZ', Name: 'DIGICELL' },
  { MobileOperatorID: 90, CountryID: 23, CountyName: 'BZ', Name: 'SMART' },
  { MobileOperatorID: 91, CountryID: 23, CountyName: 'BZ', Name: 'WiFi' },
  { MobileOperatorID: 92, CountryID: 24, CountyName: 'BJ', Name: 'MTN' },
  { MobileOperatorID: 93, CountryID: 24, CountyName: 'BJ', Name: 'WiFi' },
  { MobileOperatorID: 94, CountryID: 25, CountyName: 'BM', Name: 'CELLONE' },
  { MobileOperatorID: 95, CountryID: 25, CountyName: 'BM', Name: 'WiFi' },
  { MobileOperatorID: 96, CountryID: 26, CountyName: 'BT', Name: 'B-MOBILE' },
  { MobileOperatorID: 97, CountryID: 26, CountyName: 'BT', Name: 'TASHICELL' },
  { MobileOperatorID: 98, CountryID: 26, CountyName: 'BT', Name: 'WiFi' },
  { MobileOperatorID: 99, CountryID: 27, CountyName: 'BO', Name: 'ENTEL' },
  { MobileOperatorID: 100, CountryID: 27, CountyName: 'BO', Name: 'TIGO' },
  { MobileOperatorID: 101, CountryID: 27, CountyName: 'BO', Name: 'VIVA' },
  { MobileOperatorID: 102, CountryID: 27, CountyName: 'BO', Name: 'WiFi' },
  { MobileOperatorID: 103, CountryID: 28, CountyName: 'BA', Name: 'BH MOBILE' },
  { MobileOperatorID: 104, CountryID: 28, CountyName: 'BA', Name: 'HT-ERONET' },
  { MobileOperatorID: 105, CountryID: 28, CountyName: 'BA', Name: 'M:TEL' },
  { MobileOperatorID: 106, CountryID: 28, CountyName: 'BA', Name: 'WiFi' },
  { MobileOperatorID: 107, CountryID: 29, CountyName: 'BW', Name: 'BTC MOBILE' },
  { MobileOperatorID: 108, CountryID: 29, CountyName: 'BW', Name: 'MASCOM' },
  { MobileOperatorID: 109, CountryID: 29, CountyName: 'BW', Name: 'ORANGE' },
  { MobileOperatorID: 110, CountryID: 29, CountyName: 'BW', Name: 'WiFi' },
  { MobileOperatorID: 111, CountryID: 30, CountyName: 'BR', Name: 'CLARO' },
  { MobileOperatorID: 112, CountryID: 30, CountyName: 'BR', Name: 'CONECTA' },
  { MobileOperatorID: 113, CountryID: 30, CountyName: 'BR', Name: 'NEXTEL' },
  { MobileOperatorID: 114, CountryID: 30, CountyName: 'BR', Name: 'OI' },
  { MobileOperatorID: 115, CountryID: 30, CountyName: 'BR', Name: 'TIM' },
  { MobileOperatorID: 116, CountryID: 30, CountyName: 'BR', Name: 'VIVO' },
  { MobileOperatorID: 117, CountryID: 30, CountyName: 'BR', Name: 'WiFi' },
  { MobileOperatorID: 118, CountryID: 31, CountyName: 'IO', Name: 'WiFi' },
  { MobileOperatorID: 119, CountryID: 32, CountyName: 'VG', Name: 'DIGICEL' },
  { MobileOperatorID: 120, CountryID: 32, CountyName: 'VG', Name: 'WiFi' },
  { MobileOperatorID: 121, CountryID: 33, CountyName: 'BN', Name: 'B-MOBILE' },
  { MobileOperatorID: 122, CountryID: 33, CountyName: 'BN', Name: 'DSTCOM' },
  { MobileOperatorID: 123, CountryID: 33, CountyName: 'BN', Name: 'WiFi' },
  { MobileOperatorID: 124, CountryID: 34, CountyName: 'BG', Name: 'BULSATCOM' },
  { MobileOperatorID: 125, CountryID: 34, CountyName: 'BG', Name: 'M-TEL' },
  { MobileOperatorID: 126, CountryID: 34, CountyName: 'BG', Name: 'TELENOR' },
  { MobileOperatorID: 127, CountryID: 34, CountyName: 'BG', Name: 'VIVACOM' },
  { MobileOperatorID: 128, CountryID: 34, CountyName: 'BG', Name: 'WiFi' },
  { MobileOperatorID: 129, CountryID: 35, CountyName: 'BF', Name: 'ORANGE' },
  { MobileOperatorID: 130, CountryID: 35, CountyName: 'BF', Name: 'TELECEL FASO' },
  { MobileOperatorID: 131, CountryID: 35, CountyName: 'BF', Name: 'TELMOB' },
  { MobileOperatorID: 132, CountryID: 35, CountyName: 'BF', Name: 'WiFi' },
  { MobileOperatorID: 133, CountryID: 36, CountyName: 'MM', Name: 'MPT' },
  { MobileOperatorID: 134, CountryID: 36, CountyName: 'MM', Name: 'OOREDOO' },
  { MobileOperatorID: 135, CountryID: 36, CountyName: 'MM', Name: 'TELENOR' },
  { MobileOperatorID: 136, CountryID: 36, CountyName: 'MM', Name: 'WiFi' },
  { MobileOperatorID: 137, CountryID: 37, CountyName: 'BI', Name: 'WiFi' },
  { MobileOperatorID: 138, CountryID: 38, CountyName: 'KH', Name: 'CELLCARD' },
  { MobileOperatorID: 139, CountryID: 38, CountyName: 'KH', Name: 'QB' },
  { MobileOperatorID: 140, CountryID: 38, CountyName: 'KH', Name: 'SEATEL' },
  { MobileOperatorID: 141, CountryID: 38, CountyName: 'KH', Name: 'SMART' },
  { MobileOperatorID: 142, CountryID: 38, CountyName: 'KH', Name: 'WiFi' },
  { MobileOperatorID: 143, CountryID: 39, CountyName: 'CM', Name: 'MTN CAMEROON' },
  { MobileOperatorID: 144, CountryID: 39, CountyName: 'CM', Name: 'ORANGE' },
  { MobileOperatorID: 145, CountryID: 39, CountyName: 'CM', Name: 'WiFi' },
  { MobileOperatorID: 146, CountryID: 40, CountyName: 'CA', Name: 'BELL' },
  { MobileOperatorID: 147, CountryID: 40, CountyName: 'CA', Name: 'BELL MOBILITY VIRGIN MOBILE CANADA' },
  { MobileOperatorID: 148, CountryID: 40, CountyName: 'CA', Name: 'DMTS' },
  { MobileOperatorID: 149, CountryID: 40, CountyName: 'CA', Name: 'EASTLINK' },
  { MobileOperatorID: 150, CountryID: 40, CountyName: 'CA', Name: 'FIDO' },
  { MobileOperatorID: 151, CountryID: 40, CountyName: 'CA', Name: 'FREEDOM MOBILE' },
  { MobileOperatorID: 152, CountryID: 40, CountyName: 'CA', Name: 'ICE WIRELESS' },
  { MobileOperatorID: 153, CountryID: 40, CountyName: 'CA', Name: 'ROGERS WIRELESS' },
  { MobileOperatorID: 154, CountryID: 40, CountyName: 'CA', Name: 'SASKTEL' },
  { MobileOperatorID: 155, CountryID: 40, CountyName: 'CA', Name: 'SHAW TELECOM' },
  { MobileOperatorID: 156, CountryID: 40, CountyName: 'CA', Name: 'TELUS' },
  { MobileOperatorID: 157, CountryID: 40, CountyName: 'CA', Name: 'VIDEOTRON' },
  { MobileOperatorID: 158, CountryID: 40, CountyName: 'CA', Name: 'WiFi' },
  { MobileOperatorID: 159, CountryID: 41, CountyName: 'CV', Name: 'CVMOVEL' },
  { MobileOperatorID: 160, CountryID: 41, CountyName: 'CV', Name: 'T +' },
  { MobileOperatorID: 161, CountryID: 41, CountyName: 'CV', Name: 'WiFi' },
  { MobileOperatorID: 162, CountryID: 42, CountyName: 'KY', Name: 'DIGICEL' },
  { MobileOperatorID: 163, CountryID: 42, CountyName: 'KY', Name: 'WiFi' },
  { MobileOperatorID: 164, CountryID: 43, CountyName: 'CF', Name: 'CTP' },
  { MobileOperatorID: 165, CountryID: 43, CountyName: 'CF', Name: 'TC' },
  { MobileOperatorID: 166, CountryID: 43, CountyName: 'CF', Name: 'WiFi' },
  { MobileOperatorID: 167, CountryID: 44, CountyName: 'TD', Name: 'AIRTEL' },
  { MobileOperatorID: 168, CountryID: 44, CountyName: 'TD', Name: 'TIGO' },
  { MobileOperatorID: 169, CountryID: 44, CountyName: 'TD', Name: 'WiFi' },
  { MobileOperatorID: 170, CountryID: 45, CountyName: 'CL', Name: 'CLARO' },
  { MobileOperatorID: 171, CountryID: 45, CountyName: 'CL', Name: 'ENTEL' },
  { MobileOperatorID: 172, CountryID: 45, CountyName: 'CL', Name: 'MOVISTAR' },
  { MobileOperatorID: 173, CountryID: 45, CountyName: 'CL', Name: 'WOM' },
  { MobileOperatorID: 174, CountryID: 45, CountyName: 'CL', Name: 'WiFi' },
  { MobileOperatorID: 175, CountryID: 46, CountyName: 'CN', Name: 'CHINA MOBILE' },
  { MobileOperatorID: 176, CountryID: 46, CountyName: 'CN', Name: 'CHINA TELECOM' },
  { MobileOperatorID: 177, CountryID: 46, CountyName: 'CN', Name: 'CHINA UNICOM' },
  { MobileOperatorID: 178, CountryID: 46, CountyName: 'CN', Name: 'WiFi' },
  { MobileOperatorID: 179, CountryID: 47, CountyName: 'CX', Name: 'WiFi' },
  { MobileOperatorID: 180, CountryID: 48, CountyName: 'CC', Name: 'WiFi' },
  { MobileOperatorID: 181, CountryID: 49, CountyName: 'CO', Name: 'AVANTEL' },
  { MobileOperatorID: 182, CountryID: 49, CountyName: 'CO', Name: 'CLARO' },
  { MobileOperatorID: 183, CountryID: 49, CountyName: 'CO', Name: 'DIRECTV COLOMBIA LTDA' },
  { MobileOperatorID: 184, CountryID: 49, CountyName: 'CO', Name: 'MOVISTAR' },
  { MobileOperatorID: 185, CountryID: 49, CountyName: 'CO', Name: 'TIGO' },
  { MobileOperatorID: 186, CountryID: 49, CountyName: 'CO', Name: 'VIRGIN MOBILE' },
  { MobileOperatorID: 187, CountryID: 49, CountyName: 'CO', Name: 'WiFi' },
  { MobileOperatorID: 188, CountryID: 50, CountyName: 'KM', Name: 'WiFi' },
  { MobileOperatorID: 189, CountryID: 51, CountyName: 'CG', Name: 'AIRTEL' },
  { MobileOperatorID: 190, CountryID: 51, CountyName: 'CG', Name: 'LIBERTIS TELECOM' },
  { MobileOperatorID: 191, CountryID: 51, CountyName: 'CG', Name: 'WiFi' },
  { MobileOperatorID: 192, CountryID: 52, CountyName: 'CD', Name: 'AFRICELL' },
  { MobileOperatorID: 193, CountryID: 52, CountyName: 'CD', Name: 'ORANGE S.A.' },
  { MobileOperatorID: 194, CountryID: 52, CountyName: 'CD', Name: 'VODACOM' },
  { MobileOperatorID: 195, CountryID: 52, CountyName: 'CD', Name: 'WiFi' },
  { MobileOperatorID: 196, CountryID: 53, CountyName: 'CK', Name: 'BLUESKY' },
  { MobileOperatorID: 197, CountryID: 53, CountyName: 'CK', Name: 'WiFi' },
  { MobileOperatorID: 198, CountryID: 54, CountyName: 'CR', Name: 'CLARO' },
  { MobileOperatorID: 199, CountryID: 54, CountyName: 'CR', Name: 'KOLBI ICE' },
  { MobileOperatorID: 200, CountryID: 54, CountyName: 'CR', Name: 'MOVISTAR' },
  { MobileOperatorID: 201, CountryID: 54, CountyName: 'CR', Name: 'WiFi' },
  { MobileOperatorID: 202, CountryID: 55, CountyName: 'HR', Name: 'T-MOBILE' },
  { MobileOperatorID: 203, CountryID: 55, CountyName: 'HR', Name: 'TELE2' },
  { MobileOperatorID: 204, CountryID: 55, CountyName: 'HR', Name: 'VIP' },
  { MobileOperatorID: 205, CountryID: 55, CountyName: 'HR', Name: 'WiFi' },
  { MobileOperatorID: 206, CountryID: 56, CountyName: 'CU', Name: 'WiFi' },
  { MobileOperatorID: 207, CountryID: 57, CountyName: 'CY', Name: 'CYTAMOBILE-VODAFONE' },
  { MobileOperatorID: 208, CountryID: 57, CountyName: 'CY', Name: 'LEMONTEL' },
  { MobileOperatorID: 209, CountryID: 57, CountyName: 'CY', Name: 'MTN' },
  { MobileOperatorID: 210, CountryID: 57, CountyName: 'CY', Name: 'PRIMETEL' },
  { MobileOperatorID: 211, CountryID: 57, CountyName: 'CY', Name: 'WiFi' },
  { MobileOperatorID: 212, CountryID: 58, CountyName: 'CZ', Name: 'NORDIC TELECOM S.R.O.' },
  { MobileOperatorID: 213, CountryID: 58, CountyName: 'CZ', Name: 'O2' },
  { MobileOperatorID: 214, CountryID: 58, CountyName: 'CZ', Name: 'T-MOBILE' },
  { MobileOperatorID: 215, CountryID: 58, CountyName: 'CZ', Name: 'VODAFONE' },
  { MobileOperatorID: 216, CountryID: 58, CountyName: 'CZ', Name: 'WiFi' },
  { MobileOperatorID: 217, CountryID: 59, CountyName: 'DK', Name: '3' },
  { MobileOperatorID: 218, CountryID: 59, CountyName: 'DK', Name: 'TDC' },
  { MobileOperatorID: 219, CountryID: 59, CountyName: 'DK', Name: 'TELENOR' },
  { MobileOperatorID: 220, CountryID: 59, CountyName: 'DK', Name: 'TELIA' },
  { MobileOperatorID: 221, CountryID: 59, CountyName: 'DK', Name: 'WiFi' },
  { MobileOperatorID: 222, CountryID: 60, CountyName: 'DJ', Name: 'EVATIS' },
  { MobileOperatorID: 223, CountryID: 60, CountyName: 'DJ', Name: 'WiFi' },
  { MobileOperatorID: 224, CountryID: 61, CountyName: 'DM', Name: 'WiFi' },
  { MobileOperatorID: 225, CountryID: 62, CountyName: 'DO', Name: 'ALTICE' },
  { MobileOperatorID: 226, CountryID: 62, CountyName: 'DO', Name: 'CLARO' },
  { MobileOperatorID: 227, CountryID: 62, CountyName: 'DO', Name: 'VIVA' },
  { MobileOperatorID: 228, CountryID: 62, CountyName: 'DO', Name: 'WiFi' },
  { MobileOperatorID: 229, CountryID: 63, CountyName: 'TL', Name: 'WiFi' },
  { MobileOperatorID: 230, CountryID: 64, CountyName: 'EC', Name: 'CLARO' },
  { MobileOperatorID: 231, CountryID: 64, CountyName: 'EC', Name: 'CNT MOBILE' },
  { MobileOperatorID: 232, CountryID: 64, CountyName: 'EC', Name: 'MOVISTAR' },
  { MobileOperatorID: 233, CountryID: 64, CountyName: 'EC', Name: 'WiFi' },
  { MobileOperatorID: 234, CountryID: 65, CountyName: 'EG', Name: 'ETISALAT' },
  { MobileOperatorID: 235, CountryID: 65, CountyName: 'EG', Name: 'ORANGE' },
  { MobileOperatorID: 236, CountryID: 65, CountyName: 'EG', Name: 'VODAFONE' },
  { MobileOperatorID: 237, CountryID: 65, CountyName: 'EG', Name: 'WiFi' },
  { MobileOperatorID: 238, CountryID: 66, CountyName: 'SV', Name: 'CLARO' },
  { MobileOperatorID: 239, CountryID: 66, CountyName: 'SV', Name: 'DIGICEL' },
  { MobileOperatorID: 240, CountryID: 66, CountyName: 'SV', Name: 'MOVISTAR' },
  { MobileOperatorID: 241, CountryID: 66, CountyName: 'SV', Name: 'TIGO' },
  { MobileOperatorID: 242, CountryID: 66, CountyName: 'SV', Name: 'WiFi' },
  { MobileOperatorID: 243, CountryID: 67, CountyName: 'GQ', Name: 'ORANGE GQ' },
  { MobileOperatorID: 244, CountryID: 67, CountyName: 'GQ', Name: 'WiFi' },
  { MobileOperatorID: 245, CountryID: 68, CountyName: 'ER', Name: 'ERITEL' },
  { MobileOperatorID: 246, CountryID: 68, CountyName: 'ER', Name: 'WiFi' },
  { MobileOperatorID: 247, CountryID: 69, CountyName: 'EE', Name: 'ELISA' },
  { MobileOperatorID: 248, CountryID: 69, CountyName: 'EE', Name: 'TELE 2' },
  { MobileOperatorID: 249, CountryID: 69, CountyName: 'EE', Name: 'TELIA' },
  { MobileOperatorID: 250, CountryID: 69, CountyName: 'EE', Name: 'WiFi' },
  { MobileOperatorID: 251, CountryID: 70, CountyName: 'ET', Name: 'MTN' },
  { MobileOperatorID: 252, CountryID: 70, CountyName: 'ET', Name: 'WiFi' },
  { MobileOperatorID: 253, CountryID: 71, CountyName: 'FK', Name: 'WiFi' },
  { MobileOperatorID: 254, CountryID: 72, CountyName: 'FO', Name: 'FAROESE TELECOM' },
  { MobileOperatorID: 255, CountryID: 72, CountyName: 'FO', Name: 'VODAFONE' },
  { MobileOperatorID: 256, CountryID: 72, CountyName: 'FO', Name: 'WiFi' },
  { MobileOperatorID: 257, CountryID: 73, CountyName: 'FJ', Name: 'DIGICEL' },
  { MobileOperatorID: 258, CountryID: 73, CountyName: 'FJ', Name: 'VODAFONE' },
  { MobileOperatorID: 259, CountryID: 73, CountyName: 'FJ', Name: 'WiFi' },
  { MobileOperatorID: 260, CountryID: 74, CountyName: 'FI', Name: 'ALCOM' },
  { MobileOperatorID: 261, CountryID: 74, CountyName: 'FI', Name: 'DNA' },
  { MobileOperatorID: 262, CountryID: 74, CountyName: 'FI', Name: 'ELISA' },
  { MobileOperatorID: 263, CountryID: 74, CountyName: 'FI', Name: 'ELISA-SAUNALAHTI' },
  { MobileOperatorID: 264, CountryID: 74, CountyName: 'FI', Name: 'NOKIA SOLUTIONS AND NETWORKS OY' },
  { MobileOperatorID: 265, CountryID: 74, CountyName: 'FI', Name: 'SONERA' },
  { MobileOperatorID: 266, CountryID: 74, CountyName: 'FI', Name: 'WiFi' },
  { MobileOperatorID: 267, CountryID: 75, CountyName: 'FR', Name: 'BOUYGUES' },
  { MobileOperatorID: 268, CountryID: 75, CountyName: 'FR', Name: 'CORIOLIS TELECOM' },
  { MobileOperatorID: 269, CountryID: 75, CountyName: 'FR', Name: 'FREE MOBILE' },
  { MobileOperatorID: 270, CountryID: 75, CountyName: 'FR', Name: 'NRJ MOBILE' },
  { MobileOperatorID: 271, CountryID: 75, CountyName: 'FR', Name: 'ORANGE' },
  { MobileOperatorID: 272, CountryID: 75, CountyName: 'FR', Name: 'SFR' },
  { MobileOperatorID: 273, CountryID: 75, CountyName: 'FR', Name: 'WiFi' },
  { MobileOperatorID: 274, CountryID: 76, CountyName: 'PF', Name: 'VINI' },
  { MobileOperatorID: 275, CountryID: 76, CountyName: 'PF', Name: 'WiFi' },
  { MobileOperatorID: 276, CountryID: 77, CountyName: 'GA', Name: 'AIRTEL' },
  { MobileOperatorID: 277, CountryID: 77, CountyName: 'GA', Name: 'WiFi' },
  { MobileOperatorID: 278, CountryID: 78, CountyName: 'GM', Name: 'AFRICEL' },
  { MobileOperatorID: 279, CountryID: 78, CountyName: 'GM', Name: 'QCELL' },
  { MobileOperatorID: 280, CountryID: 78, CountyName: 'GM', Name: 'WiFi' },
  { MobileOperatorID: 281, CountryID: 79, CountyName: 'GE', Name: 'A-MOBILE' },
  { MobileOperatorID: 282, CountryID: 79, CountyName: 'GE', Name: 'BEELINE' },
  { MobileOperatorID: 283, CountryID: 79, CountyName: 'GE', Name: 'GEOCELL' },
  { MobileOperatorID: 284, CountryID: 79, CountyName: 'GE', Name: 'MAGTICOM' },
  { MobileOperatorID: 285, CountryID: 79, CountyName: 'GE', Name: 'WiFi' },
  { MobileOperatorID: 286, CountryID: 80, CountyName: 'GH', Name: 'AIRTELTIGO' },
  { MobileOperatorID: 287, CountryID: 80, CountyName: 'GH', Name: 'GLOBACOM' },
  { MobileOperatorID: 288, CountryID: 80, CountyName: 'GH', Name: 'MTN' },
  { MobileOperatorID: 289, CountryID: 80, CountyName: 'GH', Name: 'VODAFONE' },
  { MobileOperatorID: 290, CountryID: 80, CountyName: 'GH', Name: 'WiFi' },
  { MobileOperatorID: 291, CountryID: 81, CountyName: 'GI', Name: 'GIBTEL' },
  { MobileOperatorID: 292, CountryID: 81, CountyName: 'GI', Name: 'SHINE' },
  { MobileOperatorID: 293, CountryID: 81, CountyName: 'GI', Name: 'WiFi' },
  { MobileOperatorID: 294, CountryID: 82, CountyName: 'GR', Name: 'COSMOTE' },
  { MobileOperatorID: 295, CountryID: 82, CountyName: 'GR', Name: 'VODAFONE' },
  { MobileOperatorID: 296, CountryID: 82, CountyName: 'GR', Name: 'WIND' },
  { MobileOperatorID: 297, CountryID: 82, CountyName: 'GR', Name: 'WiFi' },
  { MobileOperatorID: 298, CountryID: 83, CountyName: 'GL', Name: 'WiFi' },
  { MobileOperatorID: 299, CountryID: 84, CountyName: 'GD', Name: 'WiFi' },
  { MobileOperatorID: 300, CountryID: 85, CountyName: 'GU', Name: 'WiFi' },
  { MobileOperatorID: 301, CountryID: 86, CountyName: 'GT', Name: 'CLARO' },
  { MobileOperatorID: 302, CountryID: 86, CountyName: 'GT', Name: 'MOVISTAR' },
  { MobileOperatorID: 303, CountryID: 86, CountyName: 'GT', Name: 'TIGO' },
  { MobileOperatorID: 304, CountryID: 86, CountyName: 'GT', Name: 'WiFi' },
  { MobileOperatorID: 305, CountryID: 87, CountyName: 'GN', Name: 'CELLCOM' },
  { MobileOperatorID: 306, CountryID: 87, CountyName: 'GN', Name: 'MTN' },
  { MobileOperatorID: 307, CountryID: 87, CountyName: 'GN', Name: 'ORANGE' },
  { MobileOperatorID: 308, CountryID: 87, CountyName: 'GN', Name: 'TELECEL GUINEE' },
  { MobileOperatorID: 309, CountryID: 87, CountyName: 'GN', Name: 'WiFi' },
  { MobileOperatorID: 310, CountryID: 88, CountyName: 'GW', Name: 'MTN AREEBA' },
  { MobileOperatorID: 311, CountryID: 88, CountyName: 'GW', Name: 'WiFi' },
  { MobileOperatorID: 312, CountryID: 89, CountyName: 'GY', Name: 'DIGICEL' },
  { MobileOperatorID: 313, CountryID: 89, CountyName: 'GY', Name: 'GTT CELLINK PLUS' },
  { MobileOperatorID: 314, CountryID: 89, CountyName: 'GY', Name: 'WiFi' },
  { MobileOperatorID: 315, CountryID: 90, CountyName: 'HT', Name: 'DIGICEL' },
  { MobileOperatorID: 316, CountryID: 90, CountyName: 'HT', Name: 'WiFi' },
  { MobileOperatorID: 317, CountryID: 91, CountyName: 'HN', Name: 'CLARO' },
  { MobileOperatorID: 318, CountryID: 91, CountyName: 'HN', Name: 'TIGO' },
  { MobileOperatorID: 319, CountryID: 91, CountyName: 'HN', Name: 'WiFi' },
  { MobileOperatorID: 320, CountryID: 92, CountyName: 'HK', Name: '1O1O / ONE2FREE / NEW WORLD MOBILITY / SUNMOBILE' },
  { MobileOperatorID: 321, CountryID: 92, CountyName: 'HK', Name: '3' },
  { MobileOperatorID: 322, CountryID: 92, CountyName: 'HK', Name: 'CMCC HK' },
  { MobileOperatorID: 323, CountryID: 92, CountyName: 'HK', Name: 'PCCW MOBILE 3G' },
  { MobileOperatorID: 324, CountryID: 92, CountyName: 'HK', Name: 'SMARTONE' },
  { MobileOperatorID: 325, CountryID: 92, CountyName: 'HK', Name: 'WiFi' },
  { MobileOperatorID: 326, CountryID: 93, CountyName: 'HU', Name: 'T-MOBILE' },
  { MobileOperatorID: 327, CountryID: 93, CountyName: 'HU', Name: 'TELENOR HUNGARY' },
  { MobileOperatorID: 328, CountryID: 93, CountyName: 'HU', Name: 'VODAFONE' },
  { MobileOperatorID: 329, CountryID: 93, CountyName: 'HU', Name: 'WiFi' },
  { MobileOperatorID: 330, CountryID: 94, CountyName: 'IS', Name: 'NOVA' },
  { MobileOperatorID: 331, CountryID: 94, CountyName: 'IS', Name: 'SIMINN' },
  { MobileOperatorID: 332, CountryID: 94, CountyName: 'IS', Name: 'VIKING' },
  { MobileOperatorID: 333, CountryID: 94, CountyName: 'IS', Name: 'VODAFONE' },
  { MobileOperatorID: 334, CountryID: 94, CountyName: 'IS', Name: 'WiFi' },
  { MobileOperatorID: 335, CountryID: 95, CountyName: 'IN', Name: 'AIRCEL' },
  { MobileOperatorID: 336, CountryID: 95, CountyName: 'IN', Name: 'AIRTEL' },
  { MobileOperatorID: 337, CountryID: 95, CountyName: 'IN', Name: 'CELLONE' },
  { MobileOperatorID: 338, CountryID: 95, CountyName: 'IN', Name: 'DISHNET WIRELESS' },
  { MobileOperatorID: 339, CountryID: 95, CountyName: 'IN', Name: 'IDEA' },
  { MobileOperatorID: 340, CountryID: 95, CountyName: 'IN', Name: 'JIO' },
  { MobileOperatorID: 341, CountryID: 95, CountyName: 'IN', Name: 'RELIANCE' },
  { MobileOperatorID: 342, CountryID: 95, CountyName: 'IN', Name: 'SISTEMA SHYAM' },
  { MobileOperatorID: 343, CountryID: 95, CountyName: 'IN', Name: 'TATA DOCOMO' },
  { MobileOperatorID: 344, CountryID: 95, CountyName: 'IN', Name: 'UNINOR' },
  { MobileOperatorID: 345, CountryID: 95, CountyName: 'IN', Name: 'VIDEOCON DATACOM' },
  { MobileOperatorID: 346, CountryID: 95, CountyName: 'IN', Name: 'VODAFONE INDIA' },
  { MobileOperatorID: 347, CountryID: 95, CountyName: 'IN', Name: 'WiFi' },
  { MobileOperatorID: 348, CountryID: 96, CountyName: 'ID', Name: '3' },
  { MobileOperatorID: 349, CountryID: 96, CountyName: 'ID', Name: 'CERIA' },
  { MobileOperatorID: 350, CountryID: 96, CountyName: 'ID', Name: 'ESIA' },
  { MobileOperatorID: 351, CountryID: 96, CountyName: 'ID', Name: 'INDOSAT OOREDOO' },
  { MobileOperatorID: 352, CountryID: 96, CountyName: 'ID', Name: 'SMARTFREN' },
  { MobileOperatorID: 353, CountryID: 96, CountyName: 'ID', Name: 'TELKOMSEL' },
  { MobileOperatorID: 354, CountryID: 96, CountyName: 'ID', Name: 'WiFi' },
  { MobileOperatorID: 355, CountryID: 96, CountyName: 'ID', Name: 'XL' },
  { MobileOperatorID: 356, CountryID: 97, CountyName: 'IR', Name: 'IR-MCI HAMRAH-E-AVVAL' },
  { MobileOperatorID: 357, CountryID: 97, CountyName: 'IR', Name: 'MTCE ESPADAN' },
  { MobileOperatorID: 358, CountryID: 97, CountyName: 'IR', Name: 'MTN IRANCELL' },
  { MobileOperatorID: 359, CountryID: 97, CountyName: 'IR', Name: 'RIGHTEL' },
  { MobileOperatorID: 360, CountryID: 97, CountyName: 'IR', Name: 'TKC' },
  { MobileOperatorID: 361, CountryID: 97, CountyName: 'IR', Name: 'WiFi' },
  { MobileOperatorID: 362, CountryID: 98, CountyName: 'IQ', Name: 'ASIA CELL' },
  { MobileOperatorID: 363, CountryID: 98, CountyName: 'IQ', Name: 'ITISALUNA' },
  { MobileOperatorID: 364, CountryID: 98, CountyName: 'IQ', Name: 'KOREK' },
  { MobileOperatorID: 365, CountryID: 98, CountyName: 'IQ', Name: 'WiFi' },
  { MobileOperatorID: 366, CountryID: 98, CountyName: 'IQ', Name: 'ZAIN' },
  { MobileOperatorID: 367, CountryID: 99, CountyName: 'IE', Name: '3' },
  { MobileOperatorID: 368, CountryID: 99, CountyName: 'IE', Name: 'EIR' },
  { MobileOperatorID: 369, CountryID: 99, CountyName: 'IE', Name: 'TESCO MOBILE' },
  { MobileOperatorID: 370, CountryID: 99, CountyName: 'IE', Name: 'VODAFONE' },
  { MobileOperatorID: 371, CountryID: 99, CountyName: 'IE', Name: 'WiFi' },
  { MobileOperatorID: 372, CountryID: 100, CountyName: 'IM', Name: 'WiFi' },
  { MobileOperatorID: 373, CountryID: 101, CountyName: 'IL', Name: 'WiFi' },
  { MobileOperatorID: 374, CountryID: 102, CountyName: 'IT', Name: '3 ITALIA' },
  { MobileOperatorID: 375, CountryID: 102, CountyName: 'IT', Name: 'NOVERCA' },
  { MobileOperatorID: 376, CountryID: 102, CountyName: 'IT', Name: 'POSTE MOBILE' },
  { MobileOperatorID: 377, CountryID: 102, CountyName: 'IT', Name: 'TIM' },
  { MobileOperatorID: 378, CountryID: 102, CountyName: 'IT', Name: 'VODAFONE' },
  { MobileOperatorID: 379, CountryID: 102, CountyName: 'IT', Name: 'WIND' },
  { MobileOperatorID: 380, CountryID: 102, CountyName: 'IT', Name: 'WiFi' },
  { MobileOperatorID: 381, CountryID: 103, CountyName: 'CI', Name: 'GREENN' },
  { MobileOperatorID: 382, CountryID: 103, CountyName: 'CI', Name: 'KOZ' },
  { MobileOperatorID: 383, CountryID: 103, CountyName: 'CI', Name: 'MOOV' },
  { MobileOperatorID: 384, CountryID: 103, CountyName: 'CI', Name: 'MTN' },
  { MobileOperatorID: 385, CountryID: 103, CountyName: 'CI', Name: 'ORANGE' },
  { MobileOperatorID: 386, CountryID: 103, CountyName: 'CI', Name: 'WiFi' },
  { MobileOperatorID: 387, CountryID: 104, CountyName: 'JM', Name: 'DIGICEL' },
  { MobileOperatorID: 388, CountryID: 104, CountyName: 'JM', Name: 'WiFi' },
  { MobileOperatorID: 389, CountryID: 105, CountyName: 'JP', Name: 'AU' },
  { MobileOperatorID: 390, CountryID: 105, CountyName: 'JP', Name: 'NTT DOCOMO' },
  { MobileOperatorID: 391, CountryID: 105, CountyName: 'JP', Name: 'SOFTBANK' },
  { MobileOperatorID: 392, CountryID: 105, CountyName: 'JP', Name: 'UQ WIMAX' },
  { MobileOperatorID: 393, CountryID: 105, CountyName: 'JP', Name: 'WiFi' },
  { MobileOperatorID: 394, CountryID: 105, CountyName: 'JP', Name: 'Y!MOBILE' },
  { MobileOperatorID: 395, CountryID: 106, CountyName: 'JE', Name: 'WiFi' },
  { MobileOperatorID: 396, CountryID: 107, CountyName: 'JO', Name: 'ORANGE' },
  { MobileOperatorID: 397, CountryID: 107, CountyName: 'JO', Name: 'UMNIAH' },
  { MobileOperatorID: 398, CountryID: 107, CountyName: 'JO', Name: 'WiFi' },
  { MobileOperatorID: 399, CountryID: 107, CountyName: 'JO', Name: 'ZAIN JO' },
  { MobileOperatorID: 400, CountryID: 108, CountyName: 'KZ', Name: 'ALTEL' },
  { MobileOperatorID: 401, CountryID: 108, CountyName: 'KZ', Name: 'BEELINE' },
  { MobileOperatorID: 402, CountryID: 108, CountyName: 'KZ', Name: 'KCELL' },
  { MobileOperatorID: 403, CountryID: 108, CountyName: 'KZ', Name: 'TELE2.KZ' },
  { MobileOperatorID: 404, CountryID: 108, CountyName: 'KZ', Name: 'WiFi' },
  { MobileOperatorID: 405, CountryID: 109, CountyName: 'KE', Name: 'AIRTEL' },
  { MobileOperatorID: 406, CountryID: 109, CountyName: 'KE', Name: 'SAFARICOM' },
  { MobileOperatorID: 407, CountryID: 109, CountyName: 'KE', Name: 'TELKOM' },
  { MobileOperatorID: 408, CountryID: 109, CountyName: 'KE', Name: 'WiFi' },
  { MobileOperatorID: 409, CountryID: 110, CountyName: 'KI', Name: 'KIRIBATI - TSKL' },
  { MobileOperatorID: 410, CountryID: 110, CountyName: 'KI', Name: 'WiFi' },
  { MobileOperatorID: 411, CountryID: 111, CountyName: 'KW', Name: 'K S C OOREDOO' },
  { MobileOperatorID: 412, CountryID: 111, CountyName: 'KW', Name: 'VIVA' },
  { MobileOperatorID: 413, CountryID: 111, CountyName: 'KW', Name: 'WiFi' },
  { MobileOperatorID: 414, CountryID: 111, CountyName: 'KW', Name: 'ZAIN KW' },
  { MobileOperatorID: 415, CountryID: 112, CountyName: 'KG', Name: 'BEELINE' },
  { MobileOperatorID: 416, CountryID: 112, CountyName: 'KG', Name: 'MEGACOM' },
  { MobileOperatorID: 417, CountryID: 112, CountyName: 'KG', Name: 'O!' },
  { MobileOperatorID: 418, CountryID: 112, CountyName: 'KG', Name: 'WiFi' },
  { MobileOperatorID: 419, CountryID: 113, CountyName: 'LA', Name: 'BEELINE' },
  { MobileOperatorID: 420, CountryID: 113, CountyName: 'LA', Name: 'ETL' },
  { MobileOperatorID: 421, CountryID: 113, CountyName: 'LA', Name: 'UNITEL' },
  { MobileOperatorID: 422, CountryID: 113, CountyName: 'LA', Name: 'WiFi' },
  { MobileOperatorID: 423, CountryID: 114, CountyName: 'LV', Name: 'LMT' },
  { MobileOperatorID: 424, CountryID: 114, CountyName: 'LV', Name: 'TELE2' },
  { MobileOperatorID: 425, CountryID: 114, CountyName: 'LV', Name: 'TRIATEL' },
  { MobileOperatorID: 426, CountryID: 114, CountyName: 'LV', Name: 'WiFi' },
  { MobileOperatorID: 427, CountryID: 114, CountyName: 'LV', Name: 'XOMOBILE' },
  { MobileOperatorID: 428, CountryID: 115, CountyName: 'LB', Name: 'ALFA' },
  { MobileOperatorID: 429, CountryID: 115, CountyName: 'LB', Name: 'OGERO MOBILE' },
  { MobileOperatorID: 430, CountryID: 115, CountyName: 'LB', Name: 'TOUCH' },
  { MobileOperatorID: 431, CountryID: 115, CountyName: 'LB', Name: 'WiFi' },
  { MobileOperatorID: 432, CountryID: 116, CountyName: 'LS', Name: 'ECONET TELECOM' },
  { MobileOperatorID: 433, CountryID: 116, CountyName: 'LS', Name: 'VODACOM' },
  { MobileOperatorID: 434, CountryID: 116, CountyName: 'LS', Name: 'WiFi' },
  { MobileOperatorID: 435, CountryID: 117, CountyName: 'LR', Name: 'ORANGE LBR' },
  { MobileOperatorID: 436, CountryID: 117, CountyName: 'LR', Name: 'WiFi' },
  { MobileOperatorID: 437, CountryID: 118, CountyName: 'LY', Name: 'WiFi' },
  { MobileOperatorID: 438, CountryID: 119, CountyName: 'LI', Name: 'FL1' },
  { MobileOperatorID: 439, CountryID: 119, CountyName: 'LI', Name: 'WiFi' },
  { MobileOperatorID: 440, CountryID: 120, CountyName: 'LT', Name: 'BITE' },
  { MobileOperatorID: 441, CountryID: 120, CountyName: 'LT', Name: 'TELE 2' },
  { MobileOperatorID: 442, CountryID: 120, CountyName: 'LT', Name: 'TELIA' },
  { MobileOperatorID: 443, CountryID: 120, CountyName: 'LT', Name: 'WiFi' },
  { MobileOperatorID: 444, CountryID: 121, CountyName: 'LU', Name: 'ORANGE' },
  { MobileOperatorID: 445, CountryID: 121, CountyName: 'LU', Name: 'POST' },
  { MobileOperatorID: 446, CountryID: 121, CountyName: 'LU', Name: 'TANGO' },
  { MobileOperatorID: 447, CountryID: 121, CountyName: 'LU', Name: 'WiFi' },
  { MobileOperatorID: 448, CountryID: 122, CountyName: 'MO', Name: 'CTM' },
  { MobileOperatorID: 449, CountryID: 122, CountyName: 'MO', Name: 'SMARTONE' },
  { MobileOperatorID: 450, CountryID: 122, CountyName: 'MO', Name: 'WiFi' },
  { MobileOperatorID: 451, CountryID: 123, CountyName: 'MK', Name: 'TELEKOM.MK' },
  { MobileOperatorID: 452, CountryID: 123, CountyName: 'MK', Name: 'VIP' },
  { MobileOperatorID: 453, CountryID: 123, CountyName: 'MK', Name: 'WiFi' },
  { MobileOperatorID: 454, CountryID: 124, CountyName: 'MG', Name: 'AIRTEL' },
  { MobileOperatorID: 455, CountryID: 124, CountyName: 'MG', Name: 'ORANGE' },
  { MobileOperatorID: 456, CountryID: 124, CountyName: 'MG', Name: 'TELMA' },
  { MobileOperatorID: 457, CountryID: 124, CountyName: 'MG', Name: 'WiFi' },
  { MobileOperatorID: 458, CountryID: 125, CountyName: 'MW', Name: 'AIRTEL' },
  { MobileOperatorID: 459, CountryID: 125, CountyName: 'MW', Name: 'TNM' },
  { MobileOperatorID: 460, CountryID: 125, CountyName: 'MW', Name: 'WiFi' },
  { MobileOperatorID: 461, CountryID: 126, CountyName: 'MY', Name: 'CELCOM' },
  { MobileOperatorID: 462, CountryID: 126, CountyName: 'MY', Name: 'DIGI' },
  { MobileOperatorID: 463, CountryID: 126, CountyName: 'MY', Name: 'MAXIS' },
  { MobileOperatorID: 464, CountryID: 126, CountyName: 'MY', Name: 'TM HOMELINE' },
  { MobileOperatorID: 465, CountryID: 126, CountyName: 'MY', Name: 'U MOBILE' },
  { MobileOperatorID: 466, CountryID: 126, CountyName: 'MY', Name: 'WiFi' },
  { MobileOperatorID: 467, CountryID: 127, CountyName: 'MV', Name: 'DHIRAAGU' },
  { MobileOperatorID: 468, CountryID: 127, CountyName: 'MV', Name: 'OOREDOO' },
  { MobileOperatorID: 469, CountryID: 127, CountyName: 'MV', Name: 'WiFi' },
  { MobileOperatorID: 470, CountryID: 128, CountyName: 'ML', Name: 'WiFi' },
  { MobileOperatorID: 471, CountryID: 129, CountyName: 'MT', Name: 'GO' },
  { MobileOperatorID: 472, CountryID: 129, CountyName: 'MT', Name: 'MELITA' },
  { MobileOperatorID: 473, CountryID: 129, CountyName: 'MT', Name: 'VODAFONE' },
  { MobileOperatorID: 474, CountryID: 129, CountyName: 'MT', Name: 'WiFi' },
  { MobileOperatorID: 475, CountryID: 130, CountyName: 'MH', Name: 'WiFi' },
  { MobileOperatorID: 476, CountryID: 131, CountyName: 'MR', Name: 'WiFi' },
  { MobileOperatorID: 477, CountryID: 132, CountyName: 'MU', Name: 'EMTEL' },
  { MobileOperatorID: 478, CountryID: 132, CountyName: 'MU', Name: 'WiFi' },
  { MobileOperatorID: 479, CountryID: 133, CountyName: 'YT', Name: 'WiFi' },
  { MobileOperatorID: 480, CountryID: 134, CountyName: 'MX', Name: 'ATT' },
  { MobileOperatorID: 481, CountryID: 134, CountyName: 'MX', Name: 'MOVISTAR' },
  { MobileOperatorID: 482, CountryID: 134, CountyName: 'MX', Name: 'TELCEL' },
  { MobileOperatorID: 483, CountryID: 134, CountyName: 'MX', Name: 'UNEFON' },
  { MobileOperatorID: 484, CountryID: 134, CountyName: 'MX', Name: 'WiFi' },
  { MobileOperatorID: 485, CountryID: 135, CountyName: 'FM', Name: 'WiFi' },
  { MobileOperatorID: 486, CountryID: 136, CountyName: 'MD', Name: 'MOLDCELL' },
  { MobileOperatorID: 487, CountryID: 136, CountyName: 'MD', Name: 'ORANGE' },
  { MobileOperatorID: 488, CountryID: 136, CountyName: 'MD', Name: 'WiFi' },
  { MobileOperatorID: 489, CountryID: 137, CountyName: 'MC', Name: 'WiFi' },
  { MobileOperatorID: 490, CountryID: 138, CountyName: 'MN', Name: 'G-MOBILE' },
  { MobileOperatorID: 491, CountryID: 138, CountyName: 'MN', Name: 'MOBICOM' },
  { MobileOperatorID: 492, CountryID: 138, CountyName: 'MN', Name: 'WiFi' },
  { MobileOperatorID: 493, CountryID: 139, CountyName: 'ME', Name: 'M:TEL CG' },
  { MobileOperatorID: 494, CountryID: 139, CountyName: 'ME', Name: 'T-MOBILE' },
  { MobileOperatorID: 495, CountryID: 139, CountyName: 'ME', Name: 'TELENOR' },
  { MobileOperatorID: 496, CountryID: 139, CountyName: 'ME', Name: 'WiFi' },
  { MobileOperatorID: 497, CountryID: 140, CountyName: 'MS', Name: 'WiFi' },
  { MobileOperatorID: 498, CountryID: 141, CountyName: 'MA', Name: 'IAM' },
  { MobileOperatorID: 499, CountryID: 141, CountyName: 'MA', Name: 'INWI' },
  { MobileOperatorID: 500, CountryID: 141, CountyName: 'MA', Name: 'ORANGE MOROCCO' },
  { MobileOperatorID: 501, CountryID: 141, CountyName: 'MA', Name: 'WiFi' },
  { MobileOperatorID: 502, CountryID: 142, CountyName: 'MZ', Name: 'MCEL' },
  { MobileOperatorID: 503, CountryID: 142, CountyName: 'MZ', Name: 'MOVITEL' },
  { MobileOperatorID: 504, CountryID: 142, CountyName: 'MZ', Name: 'VODACOM' },
  { MobileOperatorID: 505, CountryID: 142, CountyName: 'MZ', Name: 'WiFi' },
  { MobileOperatorID: 506, CountryID: 143, CountyName: 'NA', Name: 'MTC' },
  { MobileOperatorID: 507, CountryID: 143, CountyName: 'NA', Name: 'SWITCH' },
  { MobileOperatorID: 508, CountryID: 143, CountyName: 'NA', Name: 'TN MOBILE' },
  { MobileOperatorID: 509, CountryID: 143, CountyName: 'NA', Name: 'WiFi' },
  { MobileOperatorID: 510, CountryID: 144, CountyName: 'NR', Name: 'DIGICEL' },
  { MobileOperatorID: 511, CountryID: 144, CountyName: 'NR', Name: 'WiFi' },
  { MobileOperatorID: 512, CountryID: 145, CountyName: 'NP', Name: 'NAMASTE / NT MOBILE / SKY PHONE' },
  { MobileOperatorID: 513, CountryID: 145, CountyName: 'NP', Name: 'NCELL' },
  { MobileOperatorID: 514, CountryID: 145, CountyName: 'NP', Name: 'WiFi' },
  { MobileOperatorID: 515, CountryID: 146, CountyName: 'NL', Name: 'KPN' },
  { MobileOperatorID: 516, CountryID: 146, CountyName: 'NL', Name: 'T-MOBILE' },
  { MobileOperatorID: 517, CountryID: 146, CountyName: 'NL', Name: 'TELE2' },
  { MobileOperatorID: 518, CountryID: 146, CountyName: 'NL', Name: 'VODAFONE' },
  { MobileOperatorID: 519, CountryID: 146, CountyName: 'NL', Name: 'VOICEWORKS' },
  { MobileOperatorID: 520, CountryID: 146, CountyName: 'NL', Name: 'WiFi' },
  { MobileOperatorID: 521, CountryID: 146, CountyName: 'NL', Name: 'ZIGGO' },
  { MobileOperatorID: 522, CountryID: 147, CountyName: 'NC', Name: 'WiFi' },
  { MobileOperatorID: 523, CountryID: 148, CountyName: 'NZ', Name: '2DEGREES' },
  { MobileOperatorID: 524, CountryID: 148, CountyName: 'NZ', Name: 'SPARK' },
  { MobileOperatorID: 525, CountryID: 148, CountyName: 'NZ', Name: 'TELECOM' },
  { MobileOperatorID: 526, CountryID: 148, CountyName: 'NZ', Name: 'VODAFONE' },
  { MobileOperatorID: 527, CountryID: 148, CountyName: 'NZ', Name: 'WiFi' },
  { MobileOperatorID: 528, CountryID: 149, CountyName: 'NI', Name: 'CLARO' },
  { MobileOperatorID: 529, CountryID: 149, CountyName: 'NI', Name: 'MOVISTAR' },
  { MobileOperatorID: 530, CountryID: 149, CountyName: 'NI', Name: 'WiFi' },
  { MobileOperatorID: 531, CountryID: 150, CountyName: 'NE', Name: 'MOOV' },
  { MobileOperatorID: 532, CountryID: 150, CountyName: 'NE', Name: 'WiFi' },
  { MobileOperatorID: 533, CountryID: 151, CountyName: 'NG', Name: '9MOBILE' },
  { MobileOperatorID: 534, CountryID: 151, CountyName: 'NG', Name: 'AIRTEL' },
  { MobileOperatorID: 535, CountryID: 151, CountyName: 'NG', Name: 'GLO' },
  { MobileOperatorID: 536, CountryID: 151, CountyName: 'NG', Name: 'MTN' },
  { MobileOperatorID: 537, CountryID: 151, CountyName: 'NG', Name: 'SPECTRANET' },
  { MobileOperatorID: 538, CountryID: 151, CountyName: 'NG', Name: 'VISAFONE' },
  { MobileOperatorID: 539, CountryID: 151, CountyName: 'NG', Name: 'WiFi' },
  { MobileOperatorID: 540, CountryID: 152, CountyName: 'NU', Name: 'WiFi' },
  { MobileOperatorID: 541, CountryID: 153, CountyName: 'NF', Name: 'WiFi' },
  { MobileOperatorID: 542, CountryID: 154, CountyName: 'MP', Name: 'WiFi' },
  { MobileOperatorID: 543, CountryID: 155, CountyName: 'KP', Name: 'WiFi' },
  { MobileOperatorID: 544, CountryID: 156, CountyName: 'NO', Name: 'ICE' },
  { MobileOperatorID: 545, CountryID: 156, CountyName: 'NO', Name: 'TDC' },
  { MobileOperatorID: 546, CountryID: 156, CountyName: 'NO', Name: 'TELENOR' },
  { MobileOperatorID: 547, CountryID: 156, CountyName: 'NO', Name: 'TELIA' },
  { MobileOperatorID: 548, CountryID: 156, CountyName: 'NO', Name: 'WiFi' },
  { MobileOperatorID: 549, CountryID: 157, CountyName: 'OM', Name: 'OMANTEL' },
  { MobileOperatorID: 550, CountryID: 157, CountyName: 'OM', Name: 'OOREDOO' },
  { MobileOperatorID: 551, CountryID: 157, CountyName: 'OM', Name: 'WiFi' },
  { MobileOperatorID: 552, CountryID: 158, CountyName: 'PK', Name: 'JAZZ' },
  { MobileOperatorID: 553, CountryID: 158, CountyName: 'PK', Name: 'TELENOR' },
  { MobileOperatorID: 554, CountryID: 158, CountyName: 'PK', Name: 'UFONE' },
  { MobileOperatorID: 555, CountryID: 158, CountyName: 'PK', Name: 'WiFi' },
  { MobileOperatorID: 556, CountryID: 158, CountyName: 'PK', Name: 'ZONG' },
  { MobileOperatorID: 557, CountryID: 159, CountyName: 'PW', Name: 'WiFi' },
  { MobileOperatorID: 558, CountryID: 160, CountyName: 'PA', Name: 'CABLE WIRELESS' },
  { MobileOperatorID: 559, CountryID: 160, CountyName: 'PA', Name: 'CLARO' },
  { MobileOperatorID: 560, CountryID: 160, CountyName: 'PA', Name: 'DIGICEL' },
  { MobileOperatorID: 561, CountryID: 160, CountyName: 'PA', Name: 'MOVISTAR' },
  { MobileOperatorID: 562, CountryID: 160, CountyName: 'PA', Name: 'WiFi' },
  { MobileOperatorID: 563, CountryID: 161, CountyName: 'PG', Name: 'BMOBILE' },
  { MobileOperatorID: 564, CountryID: 161, CountyName: 'PG', Name: 'DIGICEL' },
  { MobileOperatorID: 565, CountryID: 161, CountyName: 'PG', Name: 'WiFi' },
  { MobileOperatorID: 566, CountryID: 162, CountyName: 'PY', Name: 'CLARO/HUTCHISON' },
  { MobileOperatorID: 567, CountryID: 162, CountyName: 'PY', Name: 'COPACO' },
  { MobileOperatorID: 568, CountryID: 162, CountyName: 'PY', Name: 'PERSONAL' },
  { MobileOperatorID: 569, CountryID: 162, CountyName: 'PY', Name: 'TIGO' },
  { MobileOperatorID: 570, CountryID: 162, CountyName: 'PY', Name: 'VOX' },
  { MobileOperatorID: 571, CountryID: 162, CountyName: 'PY', Name: 'WiFi' },
  { MobileOperatorID: 572, CountryID: 163, CountyName: 'PE', Name: 'BITEL' },
  { MobileOperatorID: 573, CountryID: 163, CountyName: 'PE', Name: 'CLARO' },
  { MobileOperatorID: 574, CountryID: 163, CountyName: 'PE', Name: 'ENTEL' },
  { MobileOperatorID: 575, CountryID: 163, CountyName: 'PE', Name: 'MOVISTAR' },
  { MobileOperatorID: 576, CountryID: 163, CountyName: 'PE', Name: 'WiFi' },
  { MobileOperatorID: 577, CountryID: 164, CountyName: 'PH', Name: 'GLOBE' },
  { MobileOperatorID: 578, CountryID: 164, CountyName: 'PH', Name: 'ISLACOM' },
  { MobileOperatorID: 579, CountryID: 164, CountyName: 'PH', Name: 'SMART' },
  { MobileOperatorID: 580, CountryID: 164, CountyName: 'PH', Name: 'SUN CELLULAR' },
  { MobileOperatorID: 581, CountryID: 164, CountyName: 'PH', Name: 'WiFi' },
  { MobileOperatorID: 582, CountryID: 165, CountyName: 'PN', Name: 'WiFi' },
  { MobileOperatorID: 583, CountryID: 166, CountyName: 'PL', Name: 'AERO2' },
  { MobileOperatorID: 584, CountryID: 166, CountyName: 'PL', Name: 'EZ PHONE MOBILE SP. Z O.O.' },
  { MobileOperatorID: 585, CountryID: 166, CountyName: 'PL', Name: 'ORANGE' },
  { MobileOperatorID: 586, CountryID: 166, CountyName: 'PL', Name: 'PLAY' },
  { MobileOperatorID: 587, CountryID: 166, CountyName: 'PL', Name: 'PLUS' },
  { MobileOperatorID: 588, CountryID: 166, CountyName: 'PL', Name: 'T-MOBILE' },
  { MobileOperatorID: 589, CountryID: 166, CountyName: 'PL', Name: 'TRUPHONE' },
  { MobileOperatorID: 590, CountryID: 166, CountyName: 'PL', Name: 'WiFi' },
  { MobileOperatorID: 591, CountryID: 167, CountyName: 'PT', Name: 'MEO' },
  { MobileOperatorID: 592, CountryID: 167, CountyName: 'PT', Name: 'NOS' },
  { MobileOperatorID: 593, CountryID: 167, CountyName: 'PT', Name: 'VODAFONE' },
  { MobileOperatorID: 594, CountryID: 167, CountyName: 'PT', Name: 'WiFi' },
  { MobileOperatorID: 595, CountryID: 168, CountyName: 'PR', Name: 'CLARO PUERTO RICO' },
  { MobileOperatorID: 596, CountryID: 168, CountyName: 'PR', Name: 'OPEN MOBILE' },
  { MobileOperatorID: 597, CountryID: 168, CountyName: 'PR', Name: 'WiFi' },
  { MobileOperatorID: 598, CountryID: 169, CountyName: 'QA', Name: 'OOREDOO' },
  { MobileOperatorID: 599, CountryID: 169, CountyName: 'QA', Name: 'VODAFONE' },
  { MobileOperatorID: 600, CountryID: 169, CountyName: 'QA', Name: 'WiFi' },
  { MobileOperatorID: 601, CountryID: 170, CountyName: 'RO', Name: 'DIGI.MOBIL' },
  { MobileOperatorID: 602, CountryID: 170, CountyName: 'RO', Name: 'ORANGE' },
  { MobileOperatorID: 603, CountryID: 170, CountyName: 'RO', Name: 'TELEKOM' },
  { MobileOperatorID: 604, CountryID: 170, CountyName: 'RO', Name: 'TELEKOM/ZAPP' },
  { MobileOperatorID: 605, CountryID: 170, CountyName: 'RO', Name: 'VODAFONE' },
  { MobileOperatorID: 606, CountryID: 170, CountyName: 'RO', Name: 'WiFi' },
  { MobileOperatorID: 607, CountryID: 171, CountyName: 'RU', Name: 'BAYKALWESTCOM' },
  { MobileOperatorID: 608, CountryID: 171, CountyName: 'RU', Name: 'BEELINE' },
  { MobileOperatorID: 609, CountryID: 171, CountyName: 'RU', Name: 'MEGAFON' },
  { MobileOperatorID: 610, CountryID: 171, CountyName: 'RU', Name: 'MOTIV' },
  { MobileOperatorID: 611, CountryID: 171, CountyName: 'RU', Name: 'MTS' },
  { MobileOperatorID: 612, CountryID: 171, CountyName: 'RU', Name: 'PRIMTELEFON' },
  { MobileOperatorID: 613, CountryID: 171, CountyName: 'RU', Name: 'ROSTELECOM' },
  { MobileOperatorID: 614, CountryID: 171, CountyName: 'RU', Name: 'SKYLINK' },
  { MobileOperatorID: 615, CountryID: 171, CountyName: 'RU', Name: 'SMARTS' },
  { MobileOperatorID: 616, CountryID: 171, CountyName: 'RU', Name: 'TELE2' },
  { MobileOperatorID: 617, CountryID: 171, CountyName: 'RU', Name: 'UTEL' },
  { MobileOperatorID: 618, CountryID: 171, CountyName: 'RU', Name: 'WiFi' },
  { MobileOperatorID: 619, CountryID: 172, CountyName: 'RW', Name: 'AIRTEL' },
  { MobileOperatorID: 620, CountryID: 172, CountyName: 'RW', Name: 'MTN' },
  { MobileOperatorID: 621, CountryID: 172, CountyName: 'RW', Name: 'TIGO' },
  { MobileOperatorID: 622, CountryID: 172, CountyName: 'RW', Name: 'WiFi' },
  { MobileOperatorID: 623, CountryID: 173, CountyName: 'BL', Name: 'WiFi' },
  { MobileOperatorID: 624, CountryID: 174, CountyName: 'WS', Name: 'DIGICEL' },
  { MobileOperatorID: 625, CountryID: 174, CountyName: 'WS', Name: 'WiFi' },
  { MobileOperatorID: 626, CountryID: 175, CountyName: 'SM', Name: 'WiFi' },
  { MobileOperatorID: 627, CountryID: 176, CountyName: 'ST', Name: 'WiFi' },
  { MobileOperatorID: 628, CountryID: 177, CountyName: 'SA', Name: 'AL JAWAL STC' },
  { MobileOperatorID: 629, CountryID: 177, CountyName: 'SA', Name: 'MOBILY' },
  { MobileOperatorID: 630, CountryID: 177, CountyName: 'SA', Name: 'WiFi' },
  { MobileOperatorID: 631, CountryID: 177, CountyName: 'SA', Name: 'ZAIN SA' },
  { MobileOperatorID: 632, CountryID: 178, CountyName: 'SN', Name: 'ORANGE' },
  { MobileOperatorID: 633, CountryID: 178, CountyName: 'SN', Name: 'TIGO' },
  { MobileOperatorID: 634, CountryID: 178, CountyName: 'SN', Name: 'WiFi' },
  { MobileOperatorID: 635, CountryID: 179, CountyName: 'RS', Name: 'MT:S' },
  { MobileOperatorID: 636, CountryID: 179, CountyName: 'RS', Name: 'TELENOR' },
  { MobileOperatorID: 637, CountryID: 179, CountyName: 'RS', Name: 'VIP' },
  { MobileOperatorID: 638, CountryID: 179, CountyName: 'RS', Name: 'WiFi' },
  { MobileOperatorID: 639, CountryID: 180, CountyName: 'SC', Name: 'CABLE WIRELESS' },
  { MobileOperatorID: 640, CountryID: 180, CountyName: 'SC', Name: 'WiFi' },
  { MobileOperatorID: 641, CountryID: 181, CountyName: 'SL', Name: 'AFRICELL' },
  { MobileOperatorID: 642, CountryID: 181, CountyName: 'SL', Name: 'ORANGE' },
  { MobileOperatorID: 643, CountryID: 181, CountyName: 'SL', Name: 'WiFi' },
  { MobileOperatorID: 644, CountryID: 182, CountyName: 'SG', Name: 'M1' },
  { MobileOperatorID: 645, CountryID: 182, CountyName: 'SG', Name: 'SINGTEL' },
  { MobileOperatorID: 646, CountryID: 182, CountyName: 'SG', Name: 'STARHUB' },
  { MobileOperatorID: 647, CountryID: 182, CountyName: 'SG', Name: 'WiFi' },
  { MobileOperatorID: 648, CountryID: 183, CountyName: 'SK', Name: '4KA' },
  { MobileOperatorID: 649, CountryID: 183, CountyName: 'SK', Name: 'O2' },
  { MobileOperatorID: 650, CountryID: 183, CountyName: 'SK', Name: 'ORANGE' },
  { MobileOperatorID: 651, CountryID: 183, CountyName: 'SK', Name: 'TELEKOM' },
  { MobileOperatorID: 652, CountryID: 183, CountyName: 'SK', Name: 'WiFi' },
  { MobileOperatorID: 653, CountryID: 184, CountyName: 'SI', Name: 'A1' },
  { MobileOperatorID: 654, CountryID: 184, CountyName: 'SI', Name: 'MOBITEL' },
  { MobileOperatorID: 655, CountryID: 184, CountyName: 'SI', Name: 'TELEMACH' },
  { MobileOperatorID: 656, CountryID: 184, CountyName: 'SI', Name: 'WiFi' },
  { MobileOperatorID: 657, CountryID: 185, CountyName: 'SB', Name: 'BEMOBILE' },
  { MobileOperatorID: 658, CountryID: 185, CountyName: 'SB', Name: 'BREEZE' },
  { MobileOperatorID: 659, CountryID: 185, CountyName: 'SB', Name: 'WiFi' },
  { MobileOperatorID: 660, CountryID: 186, CountyName: 'SO', Name: 'GOLIS' },
  { MobileOperatorID: 661, CountryID: 186, CountyName: 'SO', Name: 'HORMUUD' },
  { MobileOperatorID: 662, CountryID: 186, CountyName: 'SO', Name: 'SOMTEL' },
  { MobileOperatorID: 663, CountryID: 186, CountyName: 'SO', Name: 'TELESOM' },
  { MobileOperatorID: 664, CountryID: 186, CountyName: 'SO', Name: 'WiFi' },
  { MobileOperatorID: 665, CountryID: 187, CountyName: 'ZA', Name: 'CELL C' },
  { MobileOperatorID: 666, CountryID: 187, CountyName: 'ZA', Name: 'MTN' },
  { MobileOperatorID: 667, CountryID: 187, CountyName: 'ZA', Name: 'TELKOM' },
  { MobileOperatorID: 668, CountryID: 187, CountyName: 'ZA', Name: 'VODACOM' },
  { MobileOperatorID: 669, CountryID: 187, CountyName: 'ZA', Name: 'WiFi' },
  { MobileOperatorID: 670, CountryID: 188, CountyName: 'KR', Name: 'KT' },
  { MobileOperatorID: 671, CountryID: 188, CountyName: 'KR', Name: 'LG U +' },
  { MobileOperatorID: 672, CountryID: 188, CountyName: 'KR', Name: 'SKTELECOM' },
  { MobileOperatorID: 673, CountryID: 188, CountyName: 'KR', Name: 'WiFi' },
  { MobileOperatorID: 674, CountryID: 189, CountyName: 'SS', Name: 'MTN' },
  { MobileOperatorID: 675, CountryID: 189, CountyName: 'SS', Name: 'WiFi' },
  { MobileOperatorID: 676, CountryID: 189, CountyName: 'SS', Name: 'ZAIN' },
  { MobileOperatorID: 677, CountryID: 190, CountyName: 'ES', Name: 'EUSKALTEL' },
  { MobileOperatorID: 678, CountryID: 190, CountyName: 'ES', Name: 'MOBIL R' },
  { MobileOperatorID: 679, CountryID: 190, CountyName: 'ES', Name: 'MOVISTAR' },
  { MobileOperatorID: 680, CountryID: 190, CountyName: 'ES', Name: 'ORANGE' },
  { MobileOperatorID: 681, CountryID: 190, CountyName: 'ES', Name: 'TUENTI' },
  { MobileOperatorID: 682, CountryID: 190, CountyName: 'ES', Name: 'VODAFONE' },
  { MobileOperatorID: 683, CountryID: 190, CountyName: 'ES', Name: 'WiFi' },
  { MobileOperatorID: 684, CountryID: 190, CountyName: 'ES', Name: 'YOIGO' },
  { MobileOperatorID: 685, CountryID: 191, CountyName: 'LK', Name: 'AIRTEL' },
  { MobileOperatorID: 686, CountryID: 191, CountyName: 'LK', Name: 'DIALOG' },
  { MobileOperatorID: 687, CountryID: 191, CountyName: 'LK', Name: 'ETISALAT' },
  { MobileOperatorID: 688, CountryID: 191, CountyName: 'LK', Name: 'HUTCH' },
  { MobileOperatorID: 689, CountryID: 191, CountyName: 'LK', Name: 'MOBITEL' },
  { MobileOperatorID: 690, CountryID: 191, CountyName: 'LK', Name: 'WiFi' },
  { MobileOperatorID: 691, CountryID: 192, CountyName: 'SH', Name: 'WiFi' },
  { MobileOperatorID: 692, CountryID: 193, CountyName: 'KN', Name: 'WiFi' },
  { MobileOperatorID: 693, CountryID: 194, CountyName: 'LC', Name: 'DIGICEL' },
  { MobileOperatorID: 694, CountryID: 194, CountyName: 'LC', Name: 'WiFi' },
  { MobileOperatorID: 695, CountryID: 195, CountyName: 'MF', Name: 'WiFi' },
  { MobileOperatorID: 696, CountryID: 196, CountyName: 'PM', Name: 'WiFi' },
  { MobileOperatorID: 697, CountryID: 197, CountyName: 'VC', Name: 'WiFi' },
  { MobileOperatorID: 698, CountryID: 198, CountyName: 'SD', Name: 'CANAR' },
  { MobileOperatorID: 699, CountryID: 198, CountyName: 'SD', Name: 'MTN' },
  { MobileOperatorID: 700, CountryID: 198, CountyName: 'SD', Name: 'SUDANI ONE' },
  { MobileOperatorID: 701, CountryID: 198, CountyName: 'SD', Name: 'WiFi' },
  { MobileOperatorID: 702, CountryID: 198, CountyName: 'SD', Name: 'ZAIN SD' },
  { MobileOperatorID: 703, CountryID: 199, CountyName: 'SR', Name: 'DIGICEL' },
  { MobileOperatorID: 704, CountryID: 199, CountyName: 'SR', Name: 'WiFi' },
  { MobileOperatorID: 705, CountryID: 200, CountyName: 'SJ', Name: 'WiFi' },
  { MobileOperatorID: 706, CountryID: 201, CountyName: 'SZ', Name: 'SWAZI MTN' },
  { MobileOperatorID: 707, CountryID: 201, CountyName: 'SZ', Name: 'WiFi' },
  { MobileOperatorID: 708, CountryID: 202, CountyName: 'SE', Name: '3' },
  { MobileOperatorID: 709, CountryID: 202, CountyName: 'SE', Name: 'SWEDEN 3G' },
  { MobileOperatorID: 710, CountryID: 202, CountyName: 'SE', Name: 'TELE2' },
  { MobileOperatorID: 711, CountryID: 202, CountyName: 'SE', Name: 'TELENOR' },
  { MobileOperatorID: 712, CountryID: 202, CountyName: 'SE', Name: 'TELIA' },
  { MobileOperatorID: 713, CountryID: 202, CountyName: 'SE', Name: 'WiFi' },
  { MobileOperatorID: 714, CountryID: 203, CountyName: 'CH', Name: 'SALT' },
  { MobileOperatorID: 715, CountryID: 203, CountyName: 'CH', Name: 'SUNRISE' },
  { MobileOperatorID: 716, CountryID: 203, CountyName: 'CH', Name: 'SWISSCOM' },
  { MobileOperatorID: 717, CountryID: 203, CountyName: 'CH', Name: 'SWISSCOM SCHWEIZ AG' },
  { MobileOperatorID: 718, CountryID: 203, CountyName: 'CH', Name: 'UPC CABLECOM' },
  { MobileOperatorID: 719, CountryID: 203, CountyName: 'CH', Name: 'WiFi' },
  { MobileOperatorID: 720, CountryID: 204, CountyName: 'SY', Name: 'MTN' },
  { MobileOperatorID: 721, CountryID: 204, CountyName: 'SY', Name: 'SYRIATEL' },
  { MobileOperatorID: 722, CountryID: 204, CountyName: 'SY', Name: 'WiFi' },
  { MobileOperatorID: 723, CountryID: 205, CountyName: 'TW', Name: 'APTG' },
  { MobileOperatorID: 724, CountryID: 205, CountyName: 'TW', Name: 'CHUNGWA' },
  { MobileOperatorID: 725, CountryID: 205, CountyName: 'TW', Name: 'FAREASTONE' },
  { MobileOperatorID: 726, CountryID: 205, CountyName: 'TW', Name: 'T STAR' },
  { MobileOperatorID: 727, CountryID: 205, CountyName: 'TW', Name: 'TAIWAN MOBILE' },
  { MobileOperatorID: 728, CountryID: 205, CountyName: 'TW', Name: 'WiFi' },
  { MobileOperatorID: 729, CountryID: 206, CountyName: 'TJ', Name: 'WiFi' },
  { MobileOperatorID: 730, CountryID: 207, CountyName: 'TZ', Name: 'AIRTEL' },
  { MobileOperatorID: 731, CountryID: 207, CountyName: 'TZ', Name: 'TIGO' },
  { MobileOperatorID: 732, CountryID: 207, CountyName: 'TZ', Name: 'VODACOM' },
  { MobileOperatorID: 733, CountryID: 207, CountyName: 'TZ', Name: 'WiFi' },
  { MobileOperatorID: 734, CountryID: 208, CountyName: 'TH', Name: 'AIS' },
  { MobileOperatorID: 735, CountryID: 208, CountyName: 'TH', Name: 'DTAC' },
  { MobileOperatorID: 736, CountryID: 208, CountyName: 'TH', Name: 'TOT 3G' },
  { MobileOperatorID: 737, CountryID: 208, CountyName: 'TH', Name: 'TRUEMOVE' },
  { MobileOperatorID: 738, CountryID: 208, CountyName: 'TH', Name: 'TRUEMOVE H' },
  { MobileOperatorID: 739, CountryID: 208, CountyName: 'TH', Name: 'WiFi' },
  { MobileOperatorID: 740, CountryID: 209, CountyName: 'TG', Name: 'MOOV' },
  { MobileOperatorID: 741, CountryID: 209, CountyName: 'TG', Name: 'WiFi' },
  { MobileOperatorID: 742, CountryID: 210, CountyName: 'TK', Name: 'WiFi' },
  { MobileOperatorID: 743, CountryID: 211, CountyName: 'TO', Name: 'DIGICEL' },
  { MobileOperatorID: 744, CountryID: 211, CountyName: 'TO', Name: 'WiFi' },
  { MobileOperatorID: 745, CountryID: 212, CountyName: 'TT', Name: 'BMOBILE' },
  { MobileOperatorID: 746, CountryID: 212, CountyName: 'TT', Name: 'DIGICEL' },
  { MobileOperatorID: 747, CountryID: 212, CountyName: 'TT', Name: 'WiFi' },
  { MobileOperatorID: 748, CountryID: 213, CountyName: 'TN', Name: 'OOREDOO TN' },
  { MobileOperatorID: 749, CountryID: 213, CountyName: 'TN', Name: 'ORANGE' },
  { MobileOperatorID: 750, CountryID: 213, CountyName: 'TN', Name: 'TUNICELL' },
  { MobileOperatorID: 751, CountryID: 213, CountyName: 'TN', Name: 'WiFi' },
  { MobileOperatorID: 752, CountryID: 214, CountyName: 'TR', Name: 'TURK TELEKOM' },
  { MobileOperatorID: 753, CountryID: 214, CountyName: 'TR', Name: 'TURKCELL' },
  { MobileOperatorID: 754, CountryID: 214, CountyName: 'TR', Name: 'VODAFONE' },
  { MobileOperatorID: 755, CountryID: 214, CountyName: 'TR', Name: 'WiFi' },
  { MobileOperatorID: 756, CountryID: 215, CountyName: 'TM', Name: 'MTS' },
  { MobileOperatorID: 757, CountryID: 215, CountyName: 'TM', Name: 'TM-CELL' },
  { MobileOperatorID: 758, CountryID: 215, CountyName: 'TM', Name: 'WiFi' },
  { MobileOperatorID: 759, CountryID: 216, CountyName: 'TC', Name: 'WiFi' },
  { MobileOperatorID: 760, CountryID: 217, CountyName: 'TV', Name: 'WiFi' },
  { MobileOperatorID: 761, CountryID: 218, CountyName: 'AE', Name: 'DU' },
  { MobileOperatorID: 762, CountryID: 218, CountyName: 'AE', Name: 'ETISALAT' },
  { MobileOperatorID: 763, CountryID: 218, CountyName: 'AE', Name: 'WiFi' },
  { MobileOperatorID: 764, CountryID: 219, CountyName: 'UG', Name: 'AFRICELL' },
  { MobileOperatorID: 765, CountryID: 219, CountyName: 'UG', Name: 'AIRTEL' },
  { MobileOperatorID: 766, CountryID: 219, CountyName: 'UG', Name: 'MTN' },
  { MobileOperatorID: 767, CountryID: 219, CountyName: 'UG', Name: 'WiFi' },
  { MobileOperatorID: 768, CountryID: 220, CountyName: 'GB', Name: '3' },
  { MobileOperatorID: 769, CountryID: 220, CountyName: 'GB', Name: 'AIRTEL VODAFONE' },
  { MobileOperatorID: 770, CountryID: 220, CountyName: 'GB', Name: 'BT' },
  { MobileOperatorID: 771, CountryID: 220, CountyName: 'GB', Name: 'LYCAMOBILE' },
  { MobileOperatorID: 772, CountryID: 220, CountyName: 'GB', Name: 'O2 UK' },
  { MobileOperatorID: 773, CountryID: 220, CountyName: 'GB', Name: 'ORANGE UK' },
  { MobileOperatorID: 774, CountryID: 220, CountyName: 'GB', Name: 'PRONTO GSM' },
  { MobileOperatorID: 775, CountryID: 220, CountyName: 'GB', Name: 'RELISH' },
  { MobileOperatorID: 776, CountryID: 220, CountyName: 'GB', Name: 'SURE MOBILE' },
  { MobileOperatorID: 777, CountryID: 220, CountyName: 'GB', Name: 'T-MOBILE UK' },
  { MobileOperatorID: 778, CountryID: 220, CountyName: 'GB', Name: 'TALK TALK' },
  { MobileOperatorID: 779, CountryID: 220, CountyName: 'GB', Name: 'TRUPHONE' },
  { MobileOperatorID: 780, CountryID: 220, CountyName: 'GB', Name: 'VECTONE MOBILE' },
  { MobileOperatorID: 781, CountryID: 220, CountyName: 'GB', Name: 'VIRGIN MOBILE' },
  { MobileOperatorID: 782, CountryID: 220, CountyName: 'GB', Name: 'VODAFONE UK' },
  { MobileOperatorID: 783, CountryID: 220, CountyName: 'GB', Name: 'WiFi' },
  { MobileOperatorID: 784, CountryID: 221, CountyName: 'UA', Name: '3MOB' },
  { MobileOperatorID: 785, CountryID: 221, CountyName: 'UA', Name: 'KYIVSTAR' },
  { MobileOperatorID: 786, CountryID: 221, CountyName: 'UA', Name: 'LIFECELL' },
  { MobileOperatorID: 787, CountryID: 221, CountyName: 'UA', Name: 'VODAFONE' },
  { MobileOperatorID: 788, CountryID: 221, CountyName: 'UA', Name: 'WiFi' },
  { MobileOperatorID: 789, CountryID: 222, CountyName: 'UY', Name: 'ANTEL' },
  { MobileOperatorID: 790, CountryID: 222, CountyName: 'UY', Name: 'CLARO' },
  { MobileOperatorID: 791, CountryID: 222, CountyName: 'UY', Name: 'MOVISTAR' },
  { MobileOperatorID: 792, CountryID: 222, CountyName: 'UY', Name: 'WiFi' },
  { MobileOperatorID: 793, CountryID: 223, CountyName: 'US', Name: 'AERIS' },
  { MobileOperatorID: 794, CountryID: 223, CountyName: 'US', Name: 'APPALACHIAN WIRELESS' },
  { MobileOperatorID: 795, CountryID: 223, CountyName: 'US', Name: 'ASTAC' },
  { MobileOperatorID: 796, CountryID: 223, CountyName: 'US', Name: 'ATT' },
  { MobileOperatorID: 797, CountryID: 223, CountyName: 'US', Name: 'BLUEGRASS CELLULAR LLC' },
  { MobileOperatorID: 798, CountryID: 223, CountyName: 'US', Name: 'BUG TUSSEL WIRELESS' },
  { MobileOperatorID: 799, CountryID: 223, CountyName: 'US', Name: 'C SPIRE WIRELESS' },
  { MobileOperatorID: 800, CountryID: 223, CountyName: 'US', Name: 'CAROLINA WEST WIRELESS' },
  { MobileOperatorID: 801, CountryID: 223, CountyName: 'US', Name: 'CELLCOM' },
  { MobileOperatorID: 802, CountryID: 223, CountyName: 'US', Name: 'CELLULAR ONE' },
  { MobileOperatorID: 803, CountryID: 223, CountyName: 'US', Name: 'CELLULAR ONE OF EAST TEXAS' },
  { MobileOperatorID: 804, CountryID: 223, CountyName: 'US', Name: 'CINCINNATI BELL' },
  { MobileOperatorID: 805, CountryID: 223, CountyName: 'US', Name: 'ETEX WIRELESS' },
  { MobileOperatorID: 806, CountryID: 223, CountyName: 'US', Name: 'FIVE STAR WIRELESS' },
  { MobileOperatorID: 807, CountryID: 223, CountyName: 'US', Name: 'GCI' },
  { MobileOperatorID: 808, CountryID: 223, CountyName: 'US', Name: 'I WIRELESS' },
  { MobileOperatorID: 809, CountryID: 223, CountyName: 'US', Name: 'INLAND CELLULAR TELEPHONE COMPANY' },
  { MobileOperatorID: 810, CountryID: 223, CountyName: 'US', Name: 'LYCAMOBILE' },
  { MobileOperatorID: 811, CountryID: 223, CountyName: 'US', Name: 'METROPCS' },
  { MobileOperatorID: 812, CountryID: 223, CountyName: 'US', Name: 'NEWCORE' },
  { MobileOperatorID: 813, CountryID: 223, CountyName: 'US', Name: 'NEX-TECH WIRELESS' },
  { MobileOperatorID: 814, CountryID: 223, CountyName: 'US', Name: 'PIONEER CELLULAR' },
  { MobileOperatorID: 815, CountryID: 223, CountyName: 'US', Name: 'SHENTEL' },
  { MobileOperatorID: 816, CountryID: 223, CountyName: 'US', Name: 'SPRINT' },
  { MobileOperatorID: 817, CountryID: 223, CountyName: 'US', Name: 'T-MOBILE' },
  { MobileOperatorID: 818, CountryID: 223, CountyName: 'US', Name: 'U.S. CELLULAR' },
  { MobileOperatorID: 819, CountryID: 223, CountyName: 'US', Name: 'VERIZON' },
  { MobileOperatorID: 820, CountryID: 223, CountyName: 'US', Name: 'VIAERO' },
  { MobileOperatorID: 821, CountryID: 223, CountyName: 'US', Name: 'VIRGIN MOBILE' },
  { MobileOperatorID: 822, CountryID: 223, CountyName: 'US', Name: 'WEST CENTRAL' },
  { MobileOperatorID: 823, CountryID: 223, CountyName: 'US', Name: 'WiFi' },
  { MobileOperatorID: 824, CountryID: 224, CountyName: 'UZ', Name: 'BEELINE' },
  { MobileOperatorID: 825, CountryID: 224, CountyName: 'UZ', Name: 'UCELL' },
  { MobileOperatorID: 826, CountryID: 224, CountyName: 'UZ', Name: 'UMS' },
  { MobileOperatorID: 827, CountryID: 224, CountyName: 'UZ', Name: 'WiFi' },
  { MobileOperatorID: 828, CountryID: 225, CountyName: 'VU', Name: 'DIGICEL' },
  { MobileOperatorID: 829, CountryID: 225, CountyName: 'VU', Name: 'WiFi' },
  { MobileOperatorID: 830, CountryID: 226, CountyName: 'VA', Name: 'WiFi' },
  { MobileOperatorID: 831, CountryID: 227, CountyName: 'VE', Name: 'DIGITEL' },
  { MobileOperatorID: 832, CountryID: 227, CountyName: 'VE', Name: 'MOVILNET' },
  { MobileOperatorID: 833, CountryID: 227, CountyName: 'VE', Name: 'MOVISTAR' },
  { MobileOperatorID: 834, CountryID: 227, CountyName: 'VE', Name: 'WiFi' },
  { MobileOperatorID: 835, CountryID: 228, CountyName: 'VN', Name: 'GMOBILE' },
  { MobileOperatorID: 836, CountryID: 228, CountyName: 'VN', Name: 'MOBIFONE' },
  { MobileOperatorID: 837, CountryID: 228, CountyName: 'VN', Name: 'VIETNAMOBILE' },
  { MobileOperatorID: 838, CountryID: 228, CountyName: 'VN', Name: 'VIETTEL MOBILE' },
  { MobileOperatorID: 839, CountryID: 228, CountyName: 'VN', Name: 'VINAPHONE' },
  { MobileOperatorID: 840, CountryID: 228, CountyName: 'VN', Name: 'WiFi' },
  { MobileOperatorID: 841, CountryID: 229, CountyName: 'VI', Name: 'WiFi' },
  { MobileOperatorID: 842, CountryID: 230, CountyName: 'WF', Name: 'WiFi' },
  { MobileOperatorID: 843, CountryID: 231, CountyName: 'YE', Name: 'WiFi' },
  { MobileOperatorID: 844, CountryID: 231, CountyName: 'YE', Name: 'YEMEN MOBILE' },
  { MobileOperatorID: 845, CountryID: 232, CountyName: 'ZM', Name: 'AIRTEL' },
  { MobileOperatorID: 846, CountryID: 232, CountyName: 'ZM', Name: 'MTN' },
  { MobileOperatorID: 847, CountryID: 232, CountyName: 'ZM', Name: 'WiFi' },
  { MobileOperatorID: 848, CountryID: 232, CountyName: 'ZM', Name: 'ZAMTEL' },
  { MobileOperatorID: 849, CountryID: 233, CountyName: 'ZW', Name: 'ECONET' },
  { MobileOperatorID: 850, CountryID: 233, CountyName: 'ZW', Name: 'TELECEL' },
  { MobileOperatorID: 851, CountryID: 233, CountyName: 'ZW', Name: 'WiFi' },
  { MobileOperatorID: 852, CountryID: 234, CountyName: 'PS', Name: 'JAWWAL' },
  { MobileOperatorID: 853, CountryID: 234, CountyName: 'PS', Name: 'WATANIYA' },
  { MobileOperatorID: 854, CountryID: 234, CountyName: 'PS', Name: 'WiFi' },
  { MobileOperatorID: 855, CountryID: 234, CountyName: 'PS', Name: 'JAWWAL' },
  { MobileOperatorID: 856, CountryID: 234, CountyName: 'PS', Name: 'WATANIYA' },
  { MobileOperatorID: 857, CountryID: 234, CountyName: 'PS', Name: 'WiFi' },
  { MobileOperatorID: 858, CountryID: 235, CountyName: 'RE', Name: 'FREE' },
  { MobileOperatorID: 859, CountryID: 235, CountyName: 'RE', Name: 'WiFi' }
]